// Use this header to dynamically load and bind coppeliaSim.dll and its functions (call loadSimLibrary and unloadSimLibrary)

#if !defined(SIMLIB_INCLUDED_)
#define SIMLIB_INCLUDED_

#include "simConst.h"
#include "simTypes.h"

#ifdef QT_FRAMEWORK
    #include <QLibrary>
    #include <QDebug>
    #define LIBRARY QLibrary*
    #define __cdecl
    #define FARPROC void*
#else
    #ifdef _WIN32
        #include <Windows.h>
        #define LIBRARY HINSTANCE
    #elif defined (__linux) || defined (__APPLE__)
        #define __cdecl
        #define FARPROC void*
        #define LIBRARY void*
    #endif
    #include <stdio.h>
#endif // QT_FRAMEWORK

int getSimProcAddresses(LIBRARY lib);
LIBRARY loadSimLibrary(const char* pathAndFilename);
void unloadSimLibrary(LIBRARY lib);
FARPROC _getProcAddress(LIBRARY lib,const char* funcName);

typedef simInt (__cdecl *ptrSimRunSimulator)(const simChar* applicationName,simInt options,simVoid(*initCallBack)(),simVoid(*loopCallBack)(),simVoid(*deinitCallBack)());
typedef simInt (__cdecl *ptrSimRunSimulatorEx)(const simChar* applicationName,simInt options,simVoid(*initCallBack)(),simVoid(*loopCallBack)(),simVoid(*deinitCallBack)(),simInt stopDelay,const simChar* sceneOrModelToLoad);
typedef simChar* (__cdecl *ptrSimGetSimulatorMessage)(simInt* messageID,simInt* auxiliaryData,simInt* returnedDataSize);
typedef simVoid* (__cdecl *ptrSimGetMainWindow)(simInt type);
typedef simChar* (__cdecl *ptrSimGetLastError)();
typedef simInt (__cdecl *ptrSimLoadModule)(const simChar* filenameAndPath,const simChar* pluginName);
typedef simInt (__cdecl *ptrSimUnloadModule)(simInt pluginhandle);
typedef simInt (__cdecl *ptrSimSetBoolParam)(simInt Param,simBool boolState);
typedef simInt (__cdecl *ptrSimGetBoolParam)(simInt Param);
typedef simInt (__cdecl *ptrSimSetInt32Param)(simInt Param,simInt intState);
typedef simInt (__cdecl *ptrSimGetInt32Param)(simInt Param,simInt* intState);
typedef simInt (__cdecl *ptrSimGetUInt64Param)(simInt Param,simUInt64* intState);
typedef simInt (__cdecl *ptrSimSetStringParam)(simInt Param,const simChar* stringState);
typedef simChar* (__cdecl *ptrSimGetStringParam)(simInt Param);
typedef simInt (__cdecl *ptrSimSetArrayParam)(simInt Param,const simVoid* arrayOfValues);
typedef simInt (__cdecl *ptrSimGetArrayParam)(simInt Param,simVoid* arrayOfValues);
typedef simInt (__cdecl *ptrSimSetNamedStringParam)(const simChar* paramName,const simChar* stringParam,simInt paramLength);
typedef simChar* (__cdecl *ptrSimGetNamedStringParam)(const simChar* paramName,simInt* paramLength);
typedef simInt (__cdecl *ptrSimGetObject)(const simChar* objectAlias,simInt index,simInt proxy,simInt options);
typedef simInt64 (__cdecl *ptrSimGetObjectUid)(simInt objectHandle);
typedef simInt (__cdecl *ptrSimGetObjectFromUid)(simInt64 uid,simInt options);
typedef simInt (__cdecl *ptrSimGetScriptHandleEx)(simInt scriptType,simInt objHandle,const simChar* scriptName);
typedef simInt (__cdecl *ptrSimRemoveObjects)(const simInt* objectHandles,simInt count);
typedef simInt (__cdecl *ptrSimRemoveModel)(simInt objectHandle);
typedef simChar* (__cdecl *ptrSimGetObjectAlias)(simInt objectHandle,simInt options);
typedef simInt (__cdecl *ptrSimSetObjectAlias)(simInt objectHandle,const simChar* objectAlias,simInt options);
typedef simInt (__cdecl *ptrSimGetObjectParent)(simInt objectHandle);
typedef simInt (__cdecl *ptrSimGetObjectChild)(simInt objectHandle,simInt index);
typedef simInt (__cdecl *ptrSimSetObjectParent)(simInt objectHandle,simInt parentObjectHandle,simBool keepInPlace);
typedef simInt (__cdecl *ptrSimGetObjectType)(simInt objectHandle);
typedef simInt (__cdecl *ptrSimGetJointType)(simInt objectHandle);
typedef simInt (__cdecl *ptrSimReservedCommand)(simInt v,simInt w);
typedef simInt (__cdecl *ptrSimGetSimulationState)();
typedef simInt (__cdecl *ptrSimLoadScene)(const simChar* filename);
typedef simInt (__cdecl *ptrSimCloseScene)();
typedef simInt (__cdecl *ptrSimSaveScene)(const simChar* filename);
typedef simInt (__cdecl *ptrSimLoadModel)(const simChar* filename);
typedef simInt (__cdecl *ptrSimSaveModel)(int baseOfModelHandle,const simChar* filename);
typedef simInt (__cdecl *ptrSimDoesFileExist)(const simChar* filename);
typedef simInt* (__cdecl *ptrSimGetObjectSel)(simInt* cnt);
typedef simInt (__cdecl *ptrSimSetObjectSel)(const simInt* handles,simInt cnt);
typedef simInt (__cdecl *ptrSimAssociateScriptWithObject)(simInt scriptHandle,simInt associatedObjectHandle);
typedef simInt (__cdecl *ptrSimHandleMainScript)();
typedef simInt (__cdecl *ptrSimResetScript)(simInt scriptHandle);
typedef simInt (__cdecl *ptrSimAddScript)(simInt scriptProperty);
typedef simInt (__cdecl *ptrSimRemoveScript)(simInt scriptHandle);
typedef simInt (__cdecl *ptrSimRefreshDialogs)(simInt refreshDegree);
typedef simInt (__cdecl *ptrSimResetProximitySensor)(simInt sensorHandle);
typedef simChar* (__cdecl *ptrSimCreateBuffer)(simInt size);
typedef simInt (__cdecl *ptrSimReleaseBuffer)(const simChar* buffer);
typedef simInt (__cdecl *ptrSimCheckCollision)(simInt entity1Handle,simInt entity2Handle);
typedef simInt (__cdecl *ptrSimGetRealTimeSimulation)();
typedef simInt (__cdecl *ptrSimIsRealTimeSimulationStepNeeded)();
typedef simInt (__cdecl *ptrSimGetSimulationPassesPerRenderingPass)();
typedef simInt (__cdecl *ptrSimAdvanceSimulationByOneStep)();
typedef simInt (__cdecl *ptrSimStartSimulation)();
typedef simInt (__cdecl *ptrSimStopSimulation)();
typedef simInt (__cdecl *ptrSimPauseSimulation)();
typedef simChar* (__cdecl *ptrSimGetModuleName)(simInt index,simUChar* moduleVersion);
typedef simInt (__cdecl *ptrSimAdjustView)(simInt viewHandleOrIndex,simInt associatedViewableObjectHandle,simInt options,const simChar* viewLabel);
typedef simInt (__cdecl *ptrSimSetLastError)(const simChar* funcName,const simChar* errorMessage);
typedef simInt (__cdecl *ptrSimResetGraph)(simInt graphHandle);
typedef simInt (__cdecl *ptrSimDestroyGraphCurve)(simInt graphHandle,simInt curveId);
typedef simInt (__cdecl *ptrSimDuplicateGraphCurveToStatic)(simInt graphHandle,simInt curveId,const simChar* curveName);
typedef simInt (__cdecl *ptrSimSetNavigationMode)(simInt navigationMode);
typedef simInt (__cdecl *ptrSimGetNavigationMode)();
typedef simInt (__cdecl *ptrSimSetPage)(simInt index);
typedef simInt (__cdecl *ptrSimGetPage)();
typedef simInt (__cdecl *ptrSimRegisterScriptCallbackFunction)(const simChar* funcNameAtPluginName,const simChar* callTips,simVoid(*callBack)(struct SScriptCallBack* cb));
typedef simInt (__cdecl *ptrSimRegisterScriptVariable)(const simChar* varNameAtPluginName,const simChar* varValue,simInt stackHandle);
typedef simInt (__cdecl *ptrSimRegisterScriptFuncHook)(simInt scriptHandle,const simChar* funcToHook,const simChar* userFunction,simBool executeBefore,simInt options);
typedef simInt (__cdecl *ptrSimCopyPasteObjects)(simInt* objectHandles,simInt objectCount,simInt options);
typedef simInt (__cdecl *ptrSimRemoveDrawingObject)(simInt objectHandle);
typedef simInt (__cdecl *ptrSimAnnounceSceneContentChange)();
typedef simInt (__cdecl *ptrSimSetInt32Signal)(const simChar* signalName,simInt signalValue);
typedef simInt (__cdecl *ptrSimGetInt32Signal)(const simChar* signalName,simInt* signalValue);
typedef simInt (__cdecl *ptrSimClearInt32Signal)(const simChar* signalName);
typedef simInt (__cdecl *ptrSimClearFloatSignal)(const simChar* signalName);
typedef simInt (__cdecl *ptrSimSetStringSignal)(const simChar* signalName,const simChar* signalValue,simInt stringLength);
typedef simChar* (__cdecl *ptrSimGetStringSignal)(const simChar* signalName,simInt* stringLength);
typedef simInt (__cdecl *ptrSimClearStringSignal)(const simChar* signalName);
typedef simChar* (__cdecl *ptrSimGetSignalName)(simInt signalIndex,simInt signalType);
typedef simInt (__cdecl *ptrSimSetObjectProperty)(simInt objectHandle,simInt prop);
typedef simInt (__cdecl *ptrSimGetObjectProperty)(simInt objectHandle);
typedef simInt (__cdecl *ptrSimSetObjectSpecialProperty)(simInt objectHandle,simInt prop);
typedef simInt (__cdecl *ptrSimGetObjectSpecialProperty)(simInt objectHandle);
typedef simInt (__cdecl *ptrSimSetExplicitHandling)(simInt objectHandle,int explicitFlags);
typedef simInt (__cdecl *ptrSimGetExplicitHandling)(simInt objectHandle);
typedef simInt (__cdecl *ptrSimGetLinkDummy)(simInt dummyHandle);
typedef simInt (__cdecl *ptrSimSetLinkDummy)(simInt dummyHandle,simInt linkedDummyHandle);
typedef simInt (__cdecl *ptrSimSetModelProperty)(simInt objectHandle,simInt modelProperty);
typedef simInt (__cdecl *ptrSimGetModelProperty)(simInt objectHandle);
typedef simInt (__cdecl *ptrSimResetDynamicObject)(simInt objectHandle);
typedef simInt (__cdecl *ptrSimSetJointMode)(simInt jointHandle,simInt jointMode,simInt options);
typedef simInt (__cdecl *ptrSimGetJointMode)(simInt jointHandle,simInt* options);
typedef simInt (__cdecl *ptrSimSerialOpen)(const simChar* portString,simInt baudRate,simVoid* reserved1,simVoid* reserved2);
typedef simInt (__cdecl *ptrSimSerialClose)(simInt portHandle);
typedef simInt (__cdecl *ptrSimSerialSend)(simInt portHandle,const simChar* data,simInt dataLength);
typedef simInt (__cdecl *ptrSimSerialRead)(simInt portHandle,simChar* buffer,simInt dataLengthToRead);
typedef simInt (__cdecl *ptrSimSerialCheck)(simInt portHandle);
typedef simInt (__cdecl *ptrSimAuxiliaryConsoleClose)(simInt consoleHandle);
typedef simInt (__cdecl *ptrSimAuxiliaryConsoleShow)(simInt consoleHandle,simBool showState);
typedef simInt (__cdecl *ptrSimAuxiliaryConsolePrint)(simInt consoleHandle,const simChar* text);
typedef simInt (__cdecl *ptrSimGetObjectInt32Param)(simInt objectHandle,simInt parameterID,simInt* parameter);
typedef simInt (__cdecl *ptrSimSetObjectInt32Param)(simInt objectHandle,simInt parameterID,simInt parameter);
typedef simChar* (__cdecl *ptrSimGetObjectStringParam)(simInt objectHandle,simInt parameterID,simInt* parameterLength);
typedef simInt (__cdecl *ptrSimSetObjectStringParam)(simInt objectHandle,simInt parameterID,const simChar* parameter,simInt parameterLength);
typedef simInt (__cdecl *ptrSimSetSimulationPassesPerRenderingPass)(simInt p);
typedef simInt (__cdecl *ptrSimPersistentDataWrite)(const simChar* dataName,const simChar* dataValue,simInt dataLength,simInt options);
typedef simChar* (__cdecl *ptrSimPersistentDataRead)(const simChar* dataName,simInt* dataLength);
typedef simInt (__cdecl *ptrSimIsHandle)(simInt generalObjectHandle,simInt generalObjectType);
typedef simInt (__cdecl *ptrSimResetVisionSensor)(simInt visionSensorHandle);
typedef simInt (__cdecl *ptrSimSetVisionSensorImg)(simInt sensorHandle,const simUChar* img,simInt options,const simInt* pos,const simInt* size);
typedef simInt (__cdecl *ptrSimRuckigRemove)(simInt objHandle);
typedef simInt (__cdecl *ptrSimGroupShapes)(const simInt* shapeHandles,simInt shapeCount);
typedef simInt* (__cdecl *ptrSimUngroupShape)(simInt shapeHandle,simInt* shapeCount);
typedef simVoid (__cdecl *ptrSimQuitSimulator)(simBool ignoredArgument);
typedef simInt (__cdecl *ptrSimSetShapeMaterial)(simInt shapeHandle,simInt materialIdOrShapeHandle);
typedef simInt (__cdecl *ptrSimGetTextureId)(const simChar* textureName,simInt* resolution);
typedef simChar* (__cdecl *ptrSimReadTexture)(simInt textureId,simInt options,simInt posX,simInt posY,simInt sizeX,simInt sizeY);
typedef simInt (__cdecl *ptrSimWriteCustomDataBlock)(simInt objectHandle,const simChar* tagName,const simChar* data,simInt dataSize);
typedef simChar* (__cdecl *ptrSimReadCustomDataBlock)(simInt objectHandle,const simChar* tagName,simInt* dataSize);
typedef simChar* (__cdecl *ptrSimReadCustomDataBlockTags)(simInt objectHandle,simInt* tagCount);
typedef simInt (__cdecl *ptrSimGetObjects)(simInt index,simInt objectType);
typedef simInt* (__cdecl *ptrSimGetObjectsInTree)(simInt treeBaseHandle,simInt objectType,simInt options,simInt* objectCount);
typedef simInt (__cdecl *ptrSimGetShapeTextureId)(simInt shapeHandle);
typedef simInt (__cdecl *ptrSimCreateCollectionEx)(simInt options);
typedef simInt (__cdecl *ptrSimAddItemToCollection)(simInt collectionHandle,simInt what,simInt objectHandle,simInt options);
typedef simInt (__cdecl *ptrSimDestroyCollection)(simInt collectionHandle);
typedef simInt* (__cdecl *ptrSimGetCollectionObjects)(simInt collectionHandle,simInt* objectCount);
typedef simInt (__cdecl *ptrSimGetScriptInt32Param)(simInt scriptHandle,simInt parameterID,simInt* parameter);
typedef simInt (__cdecl *ptrSimSetScriptInt32Param)(simInt scriptHandle,simInt parameterID,simInt parameter);
typedef simChar* (__cdecl *ptrSimGetScriptStringParam)(simInt scriptHandle,simInt parameterID,simInt* parameterLength);
typedef simInt (__cdecl *ptrSimSetScriptStringParam)(simInt scriptHandle,simInt parameterID,const simChar* parameter,simInt parameterLength);
typedef simInt (__cdecl *ptrSimReorientShapeBoundingBox)(simInt shapeHandle,simInt relativeToHandle,simInt reservedSetToZero);
typedef simInt (__cdecl *ptrSimSaveImage)(const simUChar* image,const simInt* resolution,simInt options,const simChar* filename,simInt quality,simVoid* reserved);
typedef simUChar* (__cdecl *ptrSimLoadImage)(simInt* resolution,simInt options,const simChar* filename,simVoid* reserved);
typedef simUChar* (__cdecl *ptrSimGetScaledImage)(const simUChar* imageIn,const simInt* resolutionIn,simInt* resolutionOut,simInt options,simVoid* reserved);
typedef simInt (__cdecl *ptrSimCallScriptFunctionEx)(simInt scriptHandleOrType,const simChar* functionNameAtScriptName,simInt stackId);
typedef simChar* (__cdecl *ptrSimGetExtensionString)(simInt objectHandle,simInt index,const char* key);
typedef simInt (__cdecl *ptrSimCreateStack)();
typedef simInt (__cdecl *ptrSimReleaseStack)(simInt stackHandle);
typedef simInt (__cdecl *ptrSimCopyStack)(simInt stackHandle);
typedef simInt (__cdecl *ptrSimPushNullOntoStack)(simInt stackHandle);
typedef simInt (__cdecl *ptrSimPushBoolOntoStack)(simInt stackHandle,simBool value);
typedef simInt (__cdecl *ptrSimPushInt32OntoStack)(simInt stackHandle,simInt value);
typedef simInt (__cdecl *ptrSimPushInt64OntoStack)(simInt stackHandle,simInt64 value);
typedef simInt (__cdecl *ptrSimPushStringOntoStack)(simInt stackHandle,const simChar* value,simInt stringSize);
typedef simInt (__cdecl *ptrSimPushUInt8TableOntoStack)(simInt stackHandle,const simUChar* values,simInt valueCnt);
typedef simInt (__cdecl *ptrSimPushInt32TableOntoStack)(simInt stackHandle,const simInt* values,simInt valueCnt);
typedef simInt (__cdecl *ptrSimPushInt64TableOntoStack)(simInt stackHandle,const simInt64* values,simInt valueCnt);
typedef simInt (__cdecl *ptrSimPushTableOntoStack)(simInt stackHandle);
typedef simInt (__cdecl *ptrSimInsertDataIntoStackTable)(simInt stackHandle);
typedef simInt (__cdecl *ptrSimGetStackSize)(simInt stackHandle);
typedef simInt (__cdecl *ptrSimPopStackItem)(simInt stackHandle,simInt count);
typedef simInt (__cdecl *ptrSimMoveStackItemToTop)(simInt stackHandle,simInt cIndex);
typedef simInt (__cdecl *ptrSimIsStackValueNull)(simInt stackHandle);
typedef simInt (__cdecl *ptrSimGetStackBoolValue)(simInt stackHandle,simBool* boolValue);
typedef simInt (__cdecl *ptrSimGetStackInt32Value)(simInt stackHandle,simInt* numberValue);
typedef simInt (__cdecl *ptrSimGetStackInt64Value)(simInt stackHandle,simInt64* numberValue);
typedef simChar* (__cdecl *ptrSimGetStackStringValue)(simInt stackHandle,simInt* stringSize);
typedef simInt (__cdecl *ptrSimGetStackTableInfo)(simInt stackHandle,simInt infoType);
typedef simInt (__cdecl *ptrSimGetStackUInt8Table)(simInt stackHandle,simUChar* array,simInt count);
typedef simInt (__cdecl *ptrSimGetStackInt32Table)(simInt stackHandle,simInt* array,simInt count);
typedef simInt (__cdecl *ptrSimGetStackInt64Table)(simInt stackHandle,simInt64* array,simInt count);
typedef simInt (__cdecl *ptrSimUnfoldStackTable)(simInt stackHandle);
typedef simInt (__cdecl *ptrSimDebugStack)(simInt stackHandle,simInt cIndex);
typedef simInt (__cdecl *ptrSimGetEngineInt32Param)(simInt paramId,simInt objectHandle,const simVoid* object,simBool* ok);
typedef simBool (__cdecl *ptrSimGetEngineBoolParam)(simInt paramId,simInt objectHandle,const simVoid* object,simBool* ok);
typedef simInt (__cdecl *ptrSimSetEngineInt32Param)(simInt paramId,simInt objectHandle,const simVoid* object,simInt val);
typedef simInt (__cdecl *ptrSimSetEngineBoolParam)(simInt paramId,simInt objectHandle,const simVoid* object,simBool val);
typedef simInt (__cdecl *ptrSimInsertObjectIntoOctree)(simInt octreeHandle,simInt objectHandle,simInt options,const simUChar* color,simUInt tag,simVoid* reserved);
typedef simInt (__cdecl *ptrSimSubtractObjectFromOctree)(simInt octreeHandle,simInt objectHandle,simInt options,simVoid* reserved);
typedef simChar* (__cdecl *ptrSimOpenTextEditor)(const simChar* initText,const simChar* xml,simInt* various);
typedef simChar* (__cdecl *ptrSimPackTable)(simInt stackHandle,simInt* bufferSize);
typedef simInt (__cdecl *ptrSimUnpackTable)(simInt stackHandle,const simChar* buffer,simInt bufferSize);
typedef simInt (__cdecl *ptrSimSetReferencedHandles)(simInt objectHandle,simInt count,const simInt* referencedHandles,const simInt* reserved1,const simInt* reserved2);
typedef simInt (__cdecl *ptrSimGetReferencedHandles)(simInt objectHandle,simInt** referencedHandles,simInt** reserved1,simInt** reserved2);
typedef simInt (__cdecl *ptrSimGetShapeViz)(simInt shapeHandle,simInt index,struct SShapeVizInfo* info);
typedef simInt (__cdecl *ptrSimExecuteScriptString)(simInt scriptHandleOrType,const simChar* stringAtScriptName,simInt stackHandle);
typedef simChar* (__cdecl *ptrSimGetApiFunc)(simInt scriptHandleOrType,const simChar* apiWord);
typedef simChar* (__cdecl *ptrSimGetApiInfo)(simInt scriptHandleOrType,const simChar* apiWord);
typedef simInt (__cdecl *ptrSimSetModuleInfo)(const simChar* moduleName,simInt infoType,const simChar* stringInfo,simInt intInfo);
typedef simInt (__cdecl *ptrSimGetModuleInfo)(const simChar* moduleName,simInt infoType,simChar** stringInfo,simInt* intInfo);
typedef simInt (__cdecl *ptrSimIsDeprecated)(const simChar* funcOrConst);
typedef simChar* (__cdecl *ptrSimGetPersistentDataTags)(simInt* tagCount);
typedef simInt (__cdecl *ptrSimEventNotification)(const simChar* event);
typedef simInt (__cdecl *ptrSimAddLog)(const simChar* pluginName,simInt verbosityLevel,const simChar* logMsg);
typedef simInt (__cdecl *ptrSimIsDynamicallyEnabled)(simInt objectHandle);
typedef simInt (__cdecl *ptrSimInitScript)(simInt scriptHandle);
typedef simInt (__cdecl *ptrSimModuleEntry)(simInt handle,const simChar* label,simInt state);
typedef simInt (__cdecl *ptrSimCheckExecAuthorization)(const simChar* what,const simChar* args);
/* ------------------------------------------------------- */
typedef simInt (__cdecl *ptrSimPushFloatOntoStack)(simInt stackHandle,simFloat value);
typedef simInt (__cdecl *ptrSimPushFloatTableOntoStack)(simInt stackHandle,const simFloat* values,simInt valueCnt);
typedef simInt (__cdecl *ptrSimGetStackFloatValue)(simInt stackHandle,simFloat* numberValue);
typedef simInt (__cdecl *ptrSimGetStackFloatTable)(simInt stackHandle,simFloat* array,simInt count);
/* ------------------------------------------------------- */
typedef simInt (__cdecl *ptrSimRuckigPos)(simInt dofs,simDouble baseCycleTime,simInt flags,const simDouble* currentPos,const simDouble* currentVel,const simDouble* currentAccel,const simDouble* maxVel,const simDouble* maxAccel,const simDouble* maxJerk,const simBool* selection,const simDouble* targetPos,const simDouble* targetVel,simDouble* reserved1,simInt* reserved2);
typedef simInt (__cdecl *ptrSimRuckigVel)(simInt dofs,simDouble baseCycleTime,simInt flags,const simDouble* currentPos,const simDouble* currentVel,const simDouble* currentAccel,const simDouble* maxAccel,const simDouble* maxJerk,const simBool* selection,const simDouble* targetVel,simDouble* reserved1,simInt* reserved2);
typedef simInt (__cdecl *ptrSimRuckigStep)(simInt objHandle,simDouble cycleTime,simDouble* newPos,simDouble* newVel,simDouble* newAccel,simDouble* syncTime,simDouble* reserved1,simInt* reserved2);
typedef simInt (__cdecl *ptrSimPushDoubleOntoStack)(simInt stackHandle,simDouble value);
typedef simInt (__cdecl *ptrSimPushDoubleTableOntoStack)(simInt stackHandle,const simDouble* values,simInt valueCnt);
typedef simInt (__cdecl *ptrSimGetStackDoubleValue)(simInt stackHandle,simDouble* numberValue);
typedef simInt (__cdecl *ptrSimGetStackDoubleTable)(simInt stackHandle,simDouble* array,simInt count);
/* Following courtesy of Stephen James: */
typedef simInt (__cdecl *ptrSimExtLaunchUIThread)(const simChar* applicationName,simInt options,const simChar* sceneOrModelOrUiToLoad,const simChar* applicationDir_);
typedef simInt (__cdecl *ptrSimExtCanInitSimThread)();
typedef simInt (__cdecl *ptrSimExtSimThreadInit)();
typedef simInt (__cdecl *ptrSimExtSimThreadDestroy)();
typedef simInt (__cdecl *ptrSimExtPostExitRequest)();
typedef simInt (__cdecl *ptrSimExtGetExitRequest)();
typedef simInt (__cdecl *ptrSimExtStep)(simBool stepIfRunning);
/* non-documented functions, mainly for the dynamics plugins: */
typedef simVoid (__cdecl *ptr_simSetDynamicSimulationIconCode)(simVoid* object,simInt code);
typedef simVoid (__cdecl *ptr_simSetDynamicObjectFlagForVisualization)(simVoid* object,simInt flag);
typedef simInt (__cdecl *ptr_simGetObjectListSize)(simInt objType);
typedef const simVoid* (__cdecl *ptr_simGetObjectFromIndex)(simInt objType,simInt index);
typedef simInt (__cdecl *ptr_simGetObjectID)(const simVoid* object);
typedef simInt (__cdecl *ptr_simGetObjectType)(const simVoid* object);
typedef const simVoid** (__cdecl *ptr_simGetObjectChildren)(const simVoid* object,simInt* count);
typedef const simVoid* (__cdecl *ptr_simGetGeomProxyFromShape)(const simVoid* shape);
typedef const simVoid* (__cdecl *ptr_simGetParentObject)(const simVoid* object);
typedef const simVoid* (__cdecl *ptr_simGetObject)(int objID);
typedef const simVoid* (__cdecl *ptr_simGetIkGroupObject)(int ikGroupID);
typedef simInt (__cdecl *ptr_simMpHandleIkGroupObject)(const simVoid* ikGroup);
typedef simBool (__cdecl *ptr_simIsShapeDynamicallyStatic)(const simVoid* shape);
typedef simInt (__cdecl *ptr_simGetTreeDynamicProperty)(const simVoid* object);
typedef simInt (__cdecl *ptr_simGetDummyLinkType)(const simVoid* dummy,simInt* linkedDummyID);
typedef simInt (__cdecl *ptr_simGetJointMode)(const simVoid* joint);
typedef simBool (__cdecl *ptr_simIsJointInHybridOperation)(const simVoid* joint);
typedef simVoid (__cdecl *ptr_simDisableDynamicTreeForManipulation)(const simVoid* object,simBool disableFlag);
typedef simBool (__cdecl *ptr_simIsShapeDynamicallyRespondable)(const simVoid* shape);
typedef simInt (__cdecl *ptr_simGetDynamicCollisionMask)(const simVoid* shape);
typedef const simVoid* (__cdecl *ptr_simGetLastParentForLocalGlobalCollidable)(const simVoid* shape);
typedef simBool (__cdecl *ptr_simGetStartSleeping)(const simVoid* shape);
typedef simBool (__cdecl *ptr_simGetWasPutToSleepOnce)(const simVoid* shape);
typedef simBool (__cdecl *ptr_simGetDynamicsFullRefreshFlag)(const simVoid* object);
typedef simVoid (__cdecl *ptr_simSetDynamicsFullRefreshFlag)(const simVoid* object,simBool flag);
typedef simVoid (__cdecl *ptr_simClearAdditionalForceAndTorque)(const simVoid* shape);
typedef simInt (__cdecl *ptr_simGetJointType)(const simVoid* joint);
typedef const simVoid* (__cdecl *ptr_simGetGeomWrapFromGeomProxy)(const simVoid* geomData);
typedef simInt (__cdecl *ptr_simGetPurePrimitiveType)(const simVoid* geomInfo);
typedef simBool (__cdecl *ptr_simIsGeomWrapGeometric)(const simVoid* geomInfo);
typedef simBool (__cdecl *ptr_simIsGeomWrapConvex)(const simVoid* geomInfo);
typedef simInt (__cdecl *ptr_simGetGeometricCount)(const simVoid* geomInfo);
typedef simVoid (__cdecl *ptr_simGetAllGeometrics)(const simVoid* geomInfo,simVoid** allGeometrics);
typedef simVoid (__cdecl *ptr_simMakeDynamicAnnouncement)(int announceType);
typedef simInt (__cdecl *ptr_simGetTimeDiffInMs)(simInt previousTime);
typedef simBool (__cdecl *ptr_simDoEntitiesCollide)(simInt entity1ID,simInt entity2ID,simInt* cacheBuffer,simBool overrideCollidableFlagIfShape1,simBool overrideCollidableFlagIfShape2,simBool pathPlanningRoutineCalling);
typedef simInt (__cdecl *ptr_simGetJointDynCtrlMode)(const simVoid* joint);
typedef simInt (__cdecl *ptrSimFloatingViewRemove)(simInt floatingViewHandle);
/* previously single precision functions: */
typedef simInt (__cdecl *ptrSimSetFloatSignal)(const simChar* signalName,SIMDOUBLE signalValue);
typedef simInt (__cdecl *ptrSimGetFloatSignal)(const simChar* signalName,SIMDOUBLE* signalValue);
typedef simInt (__cdecl *ptrSimSetFloatParam)(simInt Param,SIMDOUBLE floatState);
typedef simInt (__cdecl *ptrSimGetFloatParam)(simInt Param,SIMDOUBLE* floatState);
typedef simInt (__cdecl *ptrSimGetObjectFloatParam)(simInt objectHandle,simInt parameterID,SIMDOUBLE* parameter);
typedef simInt (__cdecl *ptrSimSetObjectFloatParam)(simInt objectHandle,simInt parameterID,SIMDOUBLE parameter);
typedef SIMDOUBLE* (__cdecl *ptrSimGetObjectFloatArrayParam)(simInt objectHandle,simInt parameterID,simInt* size);
typedef simInt (__cdecl *ptrSimSetObjectFloatArrayParam)(simInt objectHandle,simInt parameterID,const SIMDOUBLE* params,simInt size);
typedef SIMDOUBLE (__cdecl *ptrSimGetEngineFloatParam)(simInt paramId,simInt objectHandle,const simVoid* object,simBool* ok);
typedef simInt (__cdecl *ptrSimSetEngineFloatParam)(simInt paramId,simInt objectHandle,const simVoid* object,SIMDOUBLE val);
typedef simInt (__cdecl *ptrSimTransformImage)(simUChar* image,const simInt* resolution,simInt options,const SIMDOUBLE* floatParams,const simInt* intParams,simVoid* reserved);
typedef const SIMDOUBLE* (__cdecl *ptrSimGetOctreeVoxels)(simInt octreeHandle,simInt* ptCnt,simVoid* reserved);
typedef const SIMDOUBLE* (__cdecl *ptrSimGetPointCloudPoints)(simInt pointCloudHandle,simInt* ptCnt,simVoid* reserved);
typedef simInt (__cdecl *ptrSimGetObjectMatrix)(simInt objectHandle,simInt relativeToObjectHandle,SIMDOUBLE* matrix);
typedef simInt (__cdecl *ptrSimSetObjectMatrix)(simInt objectHandle,simInt relativeToObjectHandle,const SIMDOUBLE* matrix);
typedef simInt (__cdecl *ptrSimGetObjectPose)(simInt objectHandle,simInt relativeToObjectHandle,SIMDOUBLE* pose);
typedef simInt (__cdecl *ptrSimSetObjectPose)(simInt objectHandle,simInt relativeToObjectHandle,const SIMDOUBLE* pose);
typedef simInt (__cdecl *ptrSimGetObjectPosition)(simInt objectHandle,simInt relativeToObjectHandle,SIMDOUBLE* position);
typedef simInt (__cdecl *ptrSimSetObjectPosition)(simInt objectHandle,simInt relativeToObjectHandle,const SIMDOUBLE* position);
typedef simInt (__cdecl *ptrSimGetObjectOrientation)(simInt objectHandle,simInt relativeToObjectHandle,SIMDOUBLE* eulerAngles);
typedef simInt (__cdecl *ptrSimSetObjectOrientation)(simInt objectHandle,simInt relativeToObjectHandle,const SIMDOUBLE* eulerAngles);
typedef simInt (__cdecl *ptrSimGetJointPosition)(simInt objectHandle,SIMDOUBLE* position);
typedef simInt (__cdecl *ptrSimSetJointPosition)(simInt objectHandle,SIMDOUBLE position);
typedef simInt (__cdecl *ptrSimSetJointTargetPosition)(simInt objectHandle,SIMDOUBLE targetPosition);
typedef simInt (__cdecl *ptrSimGetJointTargetPosition)(simInt objectHandle,SIMDOUBLE* targetPosition);
typedef simInt (__cdecl *ptrSimGetJointTargetForce)(simInt jointHandle,SIMDOUBLE* forceOrTorque);
typedef simInt (__cdecl *ptrSimSetJointTargetForce)(simInt objectHandle,SIMDOUBLE forceOrTorque,simBool signedValue);
typedef simInt (__cdecl *ptrSimGetObjectChildPose)(simInt objectHandle,SIMDOUBLE* pose);
typedef simInt (__cdecl *ptrSimSetObjectChildPose)(simInt objectHandle,const SIMDOUBLE* pose);
typedef simInt (__cdecl *ptrSimGetJointInterval)(simInt objectHandle,simBool* cyclic,SIMDOUBLE* interval);
typedef simInt (__cdecl *ptrSimSetJointInterval)(simInt objectHandle,simBool cyclic,const SIMDOUBLE* interval);
typedef simInt (__cdecl *ptrSimBuildIdentityMatrix)(SIMDOUBLE* matrix);
typedef simInt (__cdecl *ptrSimBuildMatrix)(const SIMDOUBLE* position,const SIMDOUBLE* eulerAngles,SIMDOUBLE* matrix);
typedef simInt (__cdecl *ptrSimBuildPose)(const SIMDOUBLE* position,const SIMDOUBLE* eulerAngles,SIMDOUBLE* pose);
typedef simInt (__cdecl *ptrSimGetEulerAnglesFromMatrix)(const SIMDOUBLE* matrix,SIMDOUBLE* eulerAngles);
typedef simInt (__cdecl *ptrSimInvertMatrix)(SIMDOUBLE* matrix);
typedef simInt (__cdecl *ptrSimMultiplyMatrices)(const SIMDOUBLE* matrixIn1,const SIMDOUBLE* matrixIn2,SIMDOUBLE* matrixOut);
typedef simInt (__cdecl *ptrSimMultiplyPoses)(const SIMDOUBLE* poseIn1,const SIMDOUBLE* poseIn2,SIMDOUBLE* poseOut);
typedef simInt (__cdecl *ptrSimInvertPose)(SIMDOUBLE* pose);
typedef simInt (__cdecl *ptrSimInterpolatePoses)(const SIMDOUBLE* poseIn1,const SIMDOUBLE* poseIn2,SIMDOUBLE interpolFactor,SIMDOUBLE* poseOut);
typedef simInt (__cdecl *ptrSimPoseToMatrix)(const SIMDOUBLE* poseIn,SIMDOUBLE* matrixOut);
typedef simInt (__cdecl *ptrSimMatrixToPose)(const SIMDOUBLE* matrixIn,SIMDOUBLE* poseOut);
typedef simInt (__cdecl *ptrSimInterpolateMatrices)(const SIMDOUBLE* matrixIn1,const SIMDOUBLE* matrixIn2,SIMDOUBLE interpolFactor,SIMDOUBLE* matrixOut);
typedef simInt (__cdecl *ptrSimTransformVector)(const SIMDOUBLE* matrix,SIMDOUBLE* vect);
typedef SIMDOUBLE (__cdecl *ptrSimGetSimulationTime)();
typedef SIMDOUBLE (__cdecl *ptrSimGetSystemTime)();
typedef simInt (__cdecl *ptrSimHandleProximitySensor)(simInt sensorHandle,SIMDOUBLE* detectedPoint,simInt* detectedObjectHandle,SIMDOUBLE* normalVector);
typedef simInt (__cdecl *ptrSimReadProximitySensor)(simInt sensorHandle,SIMDOUBLE* detectedPoint,simInt* detectedObjectHandle,SIMDOUBLE* normalVector);
typedef simInt (__cdecl *ptrSimHandleDynamics)(SIMDOUBLE deltaTime);
typedef simInt (__cdecl *ptrSimCheckProximitySensor)(simInt sensorHandle,simInt entityHandle,SIMDOUBLE* detectedPoint);
typedef simInt (__cdecl *ptrSimCheckProximitySensorEx)(simInt sensorHandle,simInt entityHandle,simInt detectionMode,SIMDOUBLE detectionThreshold,SIMDOUBLE maxAngle,SIMDOUBLE* detectedPoint,simInt* detectedObjectHandle,SIMDOUBLE* normalVector);
typedef simInt (__cdecl *ptrSimCheckProximitySensorEx2)(simInt sensorHandle,SIMDOUBLE* vertexPointer,simInt itemType,simInt itemCount,simInt detectionMode,SIMDOUBLE detectionThreshold,SIMDOUBLE maxAngle,SIMDOUBLE* detectedPoint,SIMDOUBLE* normalVector);
typedef simInt (__cdecl *ptrSimCheckCollisionEx)(simInt entity1Handle,simInt entity2Handle,SIMDOUBLE** intersectionSegments);
typedef simInt (__cdecl *ptrSimCheckDistance)(simInt entity1Handle,simInt entity2Handle,SIMDOUBLE threshold,SIMDOUBLE* distanceData);
typedef simInt (__cdecl *ptrSimSetSimulationTimeStep)(SIMDOUBLE timeStep);
typedef SIMDOUBLE (__cdecl *ptrSimGetSimulationTimeStep)();
typedef simInt (__cdecl *ptrSimAdjustRealTimeTimer)(simInt instanceIndex,SIMDOUBLE deltaTime);
typedef simInt (__cdecl *ptrSimFloatingViewAdd)(SIMDOUBLE posX,SIMDOUBLE posY,SIMDOUBLE sizeX,SIMDOUBLE sizeY,simInt options);
typedef simInt (__cdecl *ptrSimHandleGraph)(simInt graphHandle,SIMDOUBLE simulationTime);
typedef simInt (__cdecl *ptrSimSetGraphStreamTransformation)(simInt graphHandle,simInt streamId,simInt trType,SIMDOUBLE mult,SIMDOUBLE off,simInt movingAvgPeriod);
typedef simInt (__cdecl *ptrSimAddGraphCurve)(simInt graphHandle,const simChar* curveName,simInt dim,const simInt* streamIds,const SIMDOUBLE* defaultValues,const simChar* unitStr,simInt options,const SIMDOUBLE* color,simInt curveWidth);
typedef simInt (__cdecl *ptrSimSetGraphStreamValue)(simInt graphHandle,simInt streamId,SIMDOUBLE value);
typedef simInt (__cdecl *ptrSimSetJointTargetVelocity)(simInt objectHandle,SIMDOUBLE targetVelocity);
typedef simInt (__cdecl *ptrSimGetJointTargetVelocity)(simInt objectHandle,SIMDOUBLE* targetVelocity);
typedef simInt (__cdecl *ptrSimScaleObjects)(const simInt* objectHandles,simInt objectCount,SIMDOUBLE scalingFactor,simBool scalePositionsToo);
typedef simInt (__cdecl *ptrSimAddDrawingObject)(simInt objectType,SIMDOUBLE size,SIMDOUBLE duplicateTolerance,simInt parentObjectHandle,simInt maxItemCount,const SIMDOUBLE* color,const SIMDOUBLE* setToNULL,const SIMDOUBLE* setToNULL2,const SIMDOUBLE* setToNULL3);
typedef simInt (__cdecl *ptrSimAddGraphStream)(simInt graphHandle,const simChar* streamName,const simChar* unitStr,simInt options,const SIMDOUBLE* color,SIMDOUBLE cyclicRange);
typedef simInt (__cdecl *ptrSimAddDrawingObjectItem)(simInt objectHandle,const SIMDOUBLE* itemData);
typedef SIMDOUBLE (__cdecl *ptrSimGetObjectSizeFactor)(simInt objectHandle);
typedef simInt (__cdecl *ptrSimReadForceSensor)(simInt objectHandle,SIMDOUBLE* forceVector,SIMDOUBLE* torqueVector);
typedef simInt (__cdecl *ptrSimSetLightParameters)(simInt objectHandle,simInt state,const SIMDOUBLE* setToNULL,const SIMDOUBLE* diffusePart,const SIMDOUBLE* specularPart);
typedef simInt (__cdecl *ptrSimGetLightParameters)(simInt objectHandle,SIMDOUBLE* setToNULL,SIMDOUBLE* diffusePart,SIMDOUBLE* specularPart);
typedef simInt (__cdecl *ptrSimGetVelocity)(simInt shapeHandle,SIMDOUBLE* linearVelocity,SIMDOUBLE* angularVelocity);
typedef simInt (__cdecl *ptrSimGetObjectVelocity)(simInt objectHandle,SIMDOUBLE* linearVelocity,SIMDOUBLE* angularVelocity);
typedef simInt (__cdecl *ptrSimGetJointVelocity)(simInt jointHandle,SIMDOUBLE* velocity);
typedef simInt (__cdecl *ptrSimAddForceAndTorque)(simInt shapeHandle,const SIMDOUBLE* force,const SIMDOUBLE* torque);
typedef simInt (__cdecl *ptrSimAddForce)(simInt shapeHandle,const SIMDOUBLE* position,const SIMDOUBLE* force);
typedef simInt (__cdecl *ptrSimSetObjectColor)(simInt objectHandle,simInt index,simInt colorComponent,const SIMDOUBLE* rgbData);
typedef simInt (__cdecl *ptrSimGetObjectColor)(simInt objectHandle,simInt index,simInt colorComponent,SIMDOUBLE* rgbData);
typedef simInt (__cdecl *ptrSimSetShapeColor)(simInt shapeHandle,const simChar* colorName,simInt colorComponent,const SIMDOUBLE* rgbData);
typedef simInt (__cdecl *ptrSimGetShapeColor)(simInt shapeHandle,const simChar* colorName,simInt colorComponent,SIMDOUBLE* rgbData);
typedef simInt (__cdecl *ptrSimGetContactInfo)(simInt dynamicPass,simInt objectHandle,simInt index,simInt* objectHandles,SIMDOUBLE* contactInfo);
typedef simInt (__cdecl *ptrSimAuxiliaryConsoleOpen)(const simChar* title,simInt maxLines,simInt mode,const simInt* position,const simInt* size,const SIMDOUBLE* textColor,const SIMDOUBLE* backgroundColor);
typedef simInt (__cdecl *ptrSimImportShape)(simInt fileformat,const simChar* pathAndFilename,simInt options,SIMDOUBLE identicalVerticeTolerance,SIMDOUBLE scalingFactor);
typedef simInt (__cdecl *ptrSimImportMesh)(simInt fileformat,const simChar* pathAndFilename,simInt options,SIMDOUBLE identicalVerticeTolerance,SIMDOUBLE scalingFactor,SIMDOUBLE*** vertices,simInt** verticesSizes,simInt*** indices,simInt** indicesSizes,SIMDOUBLE*** reserved,simChar*** names);
typedef simInt (__cdecl *ptrSimExportMesh)(simInt fileformat,const simChar* pathAndFilename,simInt options,SIMDOUBLE scalingFactor,simInt elementCount,const SIMDOUBLE** vertices,const simInt* verticesSizes,const simInt** indices,const simInt* indicesSizes,SIMDOUBLE** reserved,const simChar** names);
typedef simInt (__cdecl *ptrSimCreateMeshShape)(simInt options,SIMDOUBLE shadingAngle,const SIMDOUBLE* vertices,simInt verticesSize,const simInt* indices,simInt indicesSize,SIMDOUBLE* reserved);
typedef simInt (__cdecl *ptrSimCreatePrimitiveShape)(simInt primitiveType,const SIMDOUBLE* sizes,simInt options);
typedef simInt (__cdecl *ptrSimCreateHeightfieldShape)(simInt options,SIMDOUBLE shadingAngle,simInt xPointCount,simInt yPointCount,SIMDOUBLE xSize,const SIMDOUBLE* heights);
typedef simInt (__cdecl *ptrSimGetShapeMesh)(simInt shapeHandle,SIMDOUBLE** vertices,simInt* verticesSize,simInt** indices,simInt* indicesSize,SIMDOUBLE** normals);
typedef simInt (__cdecl *ptrSimCreateJoint)(simInt jointType,simInt jointMode,simInt options,const SIMDOUBLE* sizes,const SIMDOUBLE* reservedA,const SIMDOUBLE* reservedB);
typedef simInt (__cdecl *ptrSimCreateDummy)(SIMDOUBLE size,const SIMDOUBLE* reserved);
typedef simInt (__cdecl *ptrSimCreateForceSensor)(simInt options,const simInt* intParams,const SIMDOUBLE* floatParams,const SIMDOUBLE* reserved);
typedef simInt (__cdecl *ptrSimCreateVisionSensor)(simInt options,const simInt* intParams,const SIMDOUBLE* floatParams,const SIMDOUBLE* reserved);
typedef simInt (__cdecl *ptrSimCreateProximitySensor)(simInt sensorType,simInt subType,simInt options,const simInt* intParams,const SIMDOUBLE* floatParams,const SIMDOUBLE* reserved);
typedef simInt (__cdecl *ptrSimGetRotationAxis)(const SIMDOUBLE* matrixStart,const SIMDOUBLE* matrixGoal,SIMDOUBLE* axis,SIMDOUBLE* angle);
typedef simInt (__cdecl *ptrSimRotateAroundAxis)(const SIMDOUBLE* matrixIn,const SIMDOUBLE* axis,const SIMDOUBLE* axisPos,SIMDOUBLE angle,SIMDOUBLE* matrixOut);
typedef simInt (__cdecl *ptrSimGetJointForce)(simInt jointHandle,SIMDOUBLE* forceOrTorque);
typedef simInt (__cdecl *ptrSimCameraFitToView)(simInt viewHandleOrIndex,simInt objectCount,const simInt* objectHandles,simInt options,SIMDOUBLE scaling);
typedef simInt (__cdecl *ptrSimHandleVisionSensor)(simInt visionSensorHandle,SIMDOUBLE** auxValues,simInt** auxValuesCount);
typedef simInt (__cdecl *ptrSimReadVisionSensor)(simInt visionSensorHandle,SIMDOUBLE** auxValues,simInt** auxValuesCount);
typedef simInt (__cdecl *ptrSimCheckVisionSensor)(simInt visionSensorHandle,simInt entityHandle,SIMDOUBLE** auxValues,simInt** auxValuesCount);
typedef SIMDOUBLE* (__cdecl *ptrSimCheckVisionSensorEx)(simInt visionSensorHandle,simInt entityHandle,simBool returnImage);
typedef simUChar* (__cdecl *ptrSimGetVisionSensorImg)(simInt sensorHandle,simInt options,SIMDOUBLE rgbaCutOff,const simInt* pos,const simInt* size,simInt* resolution);
typedef SIMDOUBLE* (__cdecl *ptrSimGetVisionSensorDepth)(simInt sensorHandle,simInt options,const simInt* pos,const simInt* size,simInt* resolution);
typedef simInt (__cdecl *ptrSimGetObjectQuaternion)(simInt objectHandle,simInt relativeToObjectHandle,SIMDOUBLE* quaternion);
typedef simInt (__cdecl *ptrSimSetObjectQuaternion)(simInt objectHandle,simInt relativeToObjectHandle,const SIMDOUBLE* quaternion);
typedef simInt (__cdecl *ptrSimConvexDecompose)(simInt shapeHandle,simInt options,const simInt* intParams,const SIMDOUBLE* floatParams);
typedef simInt (__cdecl *ptrSimWriteTexture)(simInt textureId,simInt options,const simChar* data,simInt posX,simInt posY,simInt sizeX,simInt sizeY,SIMDOUBLE interpol);
typedef simInt (__cdecl *ptrSimCreateTexture)(const simChar* fileName,simInt options,const SIMDOUBLE* planeSizes,const SIMDOUBLE* scalingUV,const SIMDOUBLE* xy_g,simInt fixedResolution,simInt* textureId,simInt* resolution,const simVoid* reserved);
typedef simInt (__cdecl *ptrSimGetShapeGeomInfo)(simInt shapeHandle,simInt* intData,SIMDOUBLE* floatData,simVoid* reserved);
typedef simInt (__cdecl *ptrSimScaleObject)(simInt objectHandle,SIMDOUBLE xScale,SIMDOUBLE yScale,SIMDOUBLE zScale,simInt options);
typedef simInt (__cdecl *ptrSimSetShapeTexture)(simInt shapeHandle,simInt textureId,simInt mappingMode,simInt options,const SIMDOUBLE* uvScaling,const SIMDOUBLE* position,const SIMDOUBLE* orientation);
typedef simInt (__cdecl *ptrSimGetQHull)(const SIMDOUBLE* inVertices,simInt inVerticesL,SIMDOUBLE** verticesOut,simInt* verticesOutL,simInt** indicesOut,simInt* indicesOutL,simInt reserved1,const SIMDOUBLE* reserved2);
typedef simInt (__cdecl *ptrSimGetDecimatedMesh)(const SIMDOUBLE* inVertices,simInt inVerticesL,const simInt* inIndices,simInt inIndicesL,SIMDOUBLE** verticesOut,simInt* verticesOutL,simInt** indicesOut,simInt* indicesOutL,SIMDOUBLE decimationPercent,simInt reserved1,const SIMDOUBLE* reserved2);
typedef simInt (__cdecl *ptrSimComputeMassAndInertia)(simInt shapeHandle,SIMDOUBLE density);
typedef simInt (__cdecl *ptrSimCreateOctree)(SIMDOUBLE voxelSize,simInt options,SIMDOUBLE pointSize,simVoid* reserved);
typedef simInt (__cdecl *ptrSimCreatePointCloud)(SIMDOUBLE maxVoxelSize,simInt maxPtCntPerVoxel,simInt options,SIMDOUBLE pointSize,simVoid* reserved);
typedef simInt (__cdecl *ptrSimSetPointCloudOptions)(simInt pointCloudHandle,SIMDOUBLE maxVoxelSize,simInt maxPtCntPerVoxel,simInt options,SIMDOUBLE pointSize,simVoid* reserved);
typedef simInt (__cdecl *ptrSimGetPointCloudOptions)(simInt pointCloudHandle,SIMDOUBLE* maxVoxelSize,simInt* maxPtCntPerVoxel,simInt* options,SIMDOUBLE* pointSize,simVoid* reserved);
typedef simInt (__cdecl *ptrSimInsertVoxelsIntoOctree)(simInt octreeHandle,simInt options,const SIMDOUBLE* pts,simInt ptCnt,const simUChar* color,const simUInt* tag,simVoid* reserved);
typedef simInt (__cdecl *ptrSimRemoveVoxelsFromOctree)(simInt octreeHandle,simInt options,const SIMDOUBLE* pts,simInt ptCnt,simVoid* reserved);
typedef simInt (__cdecl *ptrSimInsertPointsIntoPointCloud)(simInt pointCloudHandle,simInt options,const SIMDOUBLE* pts,simInt ptCnt,const simUChar* color,simVoid* optionalValues);
typedef simInt (__cdecl *ptrSimRemovePointsFromPointCloud)(simInt pointCloudHandle,simInt options,const SIMDOUBLE* pts,simInt ptCnt,SIMDOUBLE tolerance,simVoid* reserved);
typedef simInt (__cdecl *ptrSimIntersectPointsWithPointCloud)(simInt pointCloudHandle,simInt options,const SIMDOUBLE* pts,simInt ptCnt,SIMDOUBLE tolerance,simVoid* reserved);
typedef simInt (__cdecl *ptrSimInsertObjectIntoPointCloud)(simInt pointCloudHandle,simInt objectHandle,simInt options,SIMDOUBLE gridSize,const simUChar* color,simVoid* optionalValues);
typedef simInt (__cdecl *ptrSimSubtractObjectFromPointCloud)(simInt pointCloudHandle,simInt objectHandle,simInt options,SIMDOUBLE tolerance,simVoid* reserved);
typedef simInt (__cdecl *ptrSimCheckOctreePointOccupancy)(simInt octreeHandle,simInt options,const SIMDOUBLE* points,simInt ptCnt,simUInt* tag,simUInt64* location,simVoid* reserved);
typedef simInt (__cdecl *ptrSimApplyTexture)(simInt shapeHandle,const SIMDOUBLE* textureCoordinates,simInt textCoordSize,const simUChar* texture,const simInt* textureResolution,simInt options);
typedef simInt (__cdecl *ptrSimSetJointDependency)(simInt jointHandle,simInt masterJointHandle,SIMDOUBLE offset,SIMDOUBLE multCoeff);
typedef simInt (__cdecl *ptrSimGetJointDependency)(simInt jointHandle,simInt* masterJointHandle,SIMDOUBLE* offset,SIMDOUBLE* multCoeff);
typedef simInt (__cdecl *ptrSimGetShapeMass)(simInt shapeHandle,SIMDOUBLE* mass);
typedef simInt (__cdecl *ptrSimSetShapeMass)(simInt shapeHandle,SIMDOUBLE mass);
typedef simInt (__cdecl *ptrSimGetShapeInertia)(simInt shapeHandle,SIMDOUBLE* inertiaMatrix,SIMDOUBLE* transformationMatrix);
typedef simInt (__cdecl *ptrSimSetShapeInertia)(simInt shapeHandle,const SIMDOUBLE* inertiaMatrix,const SIMDOUBLE* transformationMatrix);
typedef simInt (__cdecl *ptrSimGenerateShapeFromPath)(const SIMDOUBLE* path,simInt pathSize,const SIMDOUBLE* section,simInt sectionSize,simInt options,const SIMDOUBLE* upVector,SIMDOUBLE reserved);
typedef SIMDOUBLE (__cdecl *ptrSimGetClosestPosOnPath)(const SIMDOUBLE* path,simInt pathSize,const SIMDOUBLE* pathLengths,const SIMDOUBLE* absPt);
typedef simInt (__cdecl *ptrSimExtCallScriptFunction)(simInt scriptHandleOrType, const simChar* functionNameAtScriptName,const simInt* inIntData, simInt inIntCnt,const SIMDOUBLE* inFloatData, simInt inFloatCnt,const simChar** inStringData, simInt inStringCnt,const simChar* inBufferData, simInt inBufferCnt,simInt** outIntData, simInt* outIntCnt,SIMDOUBLE** outFloatData, simInt* outFloatCnt,simChar*** outStringData, simInt* outStringCnt,simChar** outBufferData, simInt* outBufferSize);
typedef simVoid (__cdecl *ptr_simGetObjectLocalTransformation)(const simVoid* object,SIMDOUBLE* pos,SIMDOUBLE* quat,simBool excludeFirstJointTransformation);
typedef simVoid (__cdecl *ptr_simSetObjectLocalTransformation)(simVoid* object,const SIMDOUBLE* pos,const SIMDOUBLE* quat,SIMDOUBLE simTime);
typedef simVoid (__cdecl *ptr_simDynReportObjectCumulativeTransformation)(simVoid* object,const SIMDOUBLE* pos,const SIMDOUBLE* quat,SIMDOUBLE simTime);
typedef simVoid (__cdecl *ptr_simSetObjectCumulativeTransformation)(simVoid* object,const SIMDOUBLE* pos,const SIMDOUBLE* quat,simBool keepChildrenInPlace);
typedef simVoid (__cdecl *ptr_simGetObjectCumulativeTransformation)(const simVoid* object,SIMDOUBLE* pos,SIMDOUBLE* quat,simBool excludeFirstJointTransformation);
typedef simVoid (__cdecl *ptr_simSetJointVelocity)(const simVoid* joint,SIMDOUBLE vel);
typedef simVoid (__cdecl *ptr_simSetJointPosition)(const simVoid* joint,SIMDOUBLE pos);
typedef SIMDOUBLE (__cdecl *ptr_simGetJointPosition)(const simVoid* joint);
typedef simVoid (__cdecl *ptr_simSetDynamicMotorPositionControlTargetPosition)(const simVoid* joint,SIMDOUBLE pos);
typedef simVoid (__cdecl *ptr_simGetInitialDynamicVelocity)(const simVoid* shape,SIMDOUBLE* vel);
typedef simVoid (__cdecl *ptr_simSetInitialDynamicVelocity)(simVoid* shape,const SIMDOUBLE* vel);
typedef simVoid (__cdecl *ptr_simGetInitialDynamicAngVelocity)(const simVoid* shape,SIMDOUBLE* angularVel);
typedef simVoid (__cdecl *ptr_simSetInitialDynamicAngVelocity)(simVoid* shape,const SIMDOUBLE* angularVel);
typedef simVoid (__cdecl *ptr_simSetShapeDynamicVelocity)(simVoid* shape,const SIMDOUBLE* linear,const SIMDOUBLE* angular,SIMDOUBLE simTime);
typedef simVoid (__cdecl *ptr_simGetAdditionalForceAndTorque)(const simVoid* shape,SIMDOUBLE* force,SIMDOUBLE* torque);
typedef simBool (__cdecl *ptr_simGetJointPositionInterval)(const simVoid* joint,SIMDOUBLE* minValue,SIMDOUBLE* rangeValue);
typedef SIMDOUBLE (__cdecl *ptr_simGetDynamicMotorTargetPosition)(const simVoid* joint);
typedef SIMDOUBLE (__cdecl *ptr_simGetDynamicMotorTargetVelocity)(const simVoid* joint);
typedef SIMDOUBLE (__cdecl *ptr_simGetDynamicMotorMaxForce)(const simVoid* joint);
typedef SIMDOUBLE (__cdecl *ptr_simGetDynamicMotorUpperLimitVelocity)(const simVoid* joint);
typedef simVoid (__cdecl *ptr_simSetDynamicMotorReflectedPositionFromDynamicEngine)(simVoid* joint,SIMDOUBLE pos,SIMDOUBLE simTime);
typedef simVoid (__cdecl *ptr_simSetJointSphericalTransformation)(simVoid* joint,const SIMDOUBLE* quat,SIMDOUBLE simTime);
typedef simVoid (__cdecl *ptr_simAddForceSensorCumulativeForcesAndTorques)(simVoid* forceSensor,const SIMDOUBLE* force,const SIMDOUBLE* torque,int totalPassesCount,SIMDOUBLE simTime);
typedef simVoid (__cdecl *ptr_simAddJointCumulativeForcesOrTorques)(simVoid* joint,SIMDOUBLE forceOrTorque,int totalPassesCount,SIMDOUBLE simTime);
typedef SIMDOUBLE (__cdecl *ptr_simGetMass)(const simVoid* geomInfo);
typedef SIMDOUBLE (__cdecl *ptr_simGetLocalInertiaInfo)(const simVoid* object,SIMDOUBLE* pos,SIMDOUBLE* quat,SIMDOUBLE* diagI);
typedef simVoid (__cdecl *ptr_simGetPurePrimitiveSizes)(const simVoid* geometric,SIMDOUBLE* sizes);
typedef simVoid (__cdecl *ptr_simGetVerticesLocalFrame)(const simVoid* geometric,SIMDOUBLE* pos,SIMDOUBLE* quat);
typedef const SIMDOUBLE* (__cdecl *ptr_simGetHeightfieldData)(const simVoid* geometric,simInt* xCount,simInt* yCount,SIMDOUBLE* minHeight,SIMDOUBLE* maxHeight);
typedef simVoid (__cdecl *ptr_simGetCumulativeMeshes)(const simVoid* geomInfo,SIMDOUBLE** vertices,simInt* verticesSize,simInt** indices,simInt* indicesSize);
typedef simVoid (__cdecl *ptr_simGetGravity)(SIMDOUBLE* gravity);
typedef simBool (__cdecl *ptr_simGetDistanceBetweenEntitiesIfSmaller)(simInt entity1ID,simInt entity2ID,SIMDOUBLE* distance,SIMDOUBLE* ray,simInt* cacheBuffer,simBool overrideMeasurableFlagIfNonCollection1,simBool overrideMeasurableFlagIfNonCollection2,simBool pathPlanningRoutineCalling);
typedef simInt (__cdecl *ptr_simHandleJointControl)(const simVoid* joint,simInt auxV,const simInt* inputValuesInt,const SIMDOUBLE* inputValuesFloat,SIMDOUBLE* outputValues);
typedef simInt (__cdecl *ptr_simHandleCustomContact)(simInt objHandle1,simInt objHandle2,simInt engine,simInt* dataInt,SIMDOUBLE* dataFloat);
typedef SIMDOUBLE (__cdecl *ptr_simGetPureHollowScaling)(const simVoid* geometric);
typedef simVoid (__cdecl *ptr_simDynCallback)(const simInt* intData,const SIMDOUBLE* floatData);


extern ptrSimRunSimulator simRunSimulator;
extern ptrSimRunSimulatorEx simRunSimulatorEx;
extern ptrSimGetSimulatorMessage simGetSimulatorMessage;
extern ptrSimGetMainWindow simGetMainWindow;
extern ptrSimGetLastError simGetLastError;
extern ptrSimLoadModule simLoadModule;
extern ptrSimUnloadModule simUnloadModule;
extern ptrSimSetBoolParam simSetBoolParam;
extern ptrSimGetBoolParam simGetBoolParam;
extern ptrSimSetInt32Param simSetInt32Param;
extern ptrSimGetInt32Param simGetInt32Param;
extern ptrSimGetUInt64Param simGetUInt64Param;
extern ptrSimSetFloatParam simSetFloatParam;
extern ptrSimGetFloatParam simGetFloatParam;
extern ptrSimSetStringParam simSetStringParam;
extern ptrSimGetStringParam simGetStringParam;
extern ptrSimSetArrayParam simSetArrayParam;
extern ptrSimGetArrayParam simGetArrayParam;
extern ptrSimSetNamedStringParam simSetNamedStringParam;
extern ptrSimGetNamedStringParam simGetNamedStringParam;
extern ptrSimGetObject simGetObject;
extern ptrSimGetObjectUid simGetObjectUid;
extern ptrSimGetObjectFromUid simGetObjectFromUid;
extern ptrSimGetScriptHandleEx simGetScriptHandleEx;
extern ptrSimRemoveObjects simRemoveObjects;
extern ptrSimRemoveModel simRemoveModel;
extern ptrSimGetObjectAlias simGetObjectAlias;
extern ptrSimSetObjectAlias simSetObjectAlias;
extern ptrSimGetObjectMatrix simGetObjectMatrix;
extern ptrSimSetObjectMatrix simSetObjectMatrix;
extern ptrSimGetObjectPose simGetObjectPose;
extern ptrSimSetObjectPose simSetObjectPose;
extern ptrSimGetObjectPosition simGetObjectPosition;
extern ptrSimSetObjectPosition simSetObjectPosition;
extern ptrSimGetObjectOrientation simGetObjectOrientation;
extern ptrSimSetObjectOrientation simSetObjectOrientation;
extern ptrSimGetJointPosition simGetJointPosition;
extern ptrSimSetJointPosition simSetJointPosition;
extern ptrSimSetJointTargetPosition simSetJointTargetPosition;
extern ptrSimGetJointTargetPosition simGetJointTargetPosition;
extern ptrSimGetObjectChildPose simGetObjectChildPose;
extern ptrSimSetObjectChildPose simSetObjectChildPose;
extern ptrSimGetJointInterval simGetJointInterval;
extern ptrSimSetJointInterval simSetJointInterval;
extern ptrSimGetObjectParent simGetObjectParent;
extern ptrSimGetObjectChild simGetObjectChild;
extern ptrSimSetObjectParent simSetObjectParent;
extern ptrSimGetObjectType simGetObjectType;
extern ptrSimGetJointType simGetJointType;
extern ptrSimBuildIdentityMatrix simBuildIdentityMatrix;
extern ptrSimBuildMatrix simBuildMatrix;
extern ptrSimBuildPose simBuildPose;
extern ptrSimGetEulerAnglesFromMatrix simGetEulerAnglesFromMatrix;
extern ptrSimInvertMatrix simInvertMatrix;
extern ptrSimMultiplyMatrices simMultiplyMatrices;
extern ptrSimMultiplyPoses simMultiplyPoses;
extern ptrSimInvertPose simInvertPose;
extern ptrSimInterpolatePoses simInterpolatePoses;
extern ptrSimPoseToMatrix simPoseToMatrix;
extern ptrSimMatrixToPose simMatrixToPose;
extern ptrSimInterpolateMatrices simInterpolateMatrices;
extern ptrSimTransformVector simTransformVector;
extern ptrSimReservedCommand simReservedCommand;
extern ptrSimGetSimulationTime simGetSimulationTime;
extern ptrSimGetSimulationState simGetSimulationState;
extern ptrSimGetSystemTime simGetSystemTime;
extern ptrSimLoadScene simLoadScene;
extern ptrSimCloseScene simCloseScene;
extern ptrSimSaveScene simSaveScene;
extern ptrSimLoadModel simLoadModel;
extern ptrSimSaveModel simSaveModel;
extern ptrSimDoesFileExist simDoesFileExist;
extern ptrSimGetObjectSel simGetObjectSel;
extern ptrSimSetObjectSel simSetObjectSel;
extern ptrSimHandleProximitySensor simHandleProximitySensor;
extern ptrSimReadProximitySensor simReadProximitySensor;
extern ptrSimHandleDynamics simHandleDynamics;
extern ptrSimAssociateScriptWithObject simAssociateScriptWithObject;
extern ptrSimHandleMainScript simHandleMainScript;
extern ptrSimResetScript simResetScript;
extern ptrSimAddScript simAddScript;
extern ptrSimRemoveScript simRemoveScript;
extern ptrSimRefreshDialogs simRefreshDialogs;
extern ptrSimResetProximitySensor simResetProximitySensor;
extern ptrSimCheckProximitySensor simCheckProximitySensor;
extern ptrSimCheckProximitySensorEx simCheckProximitySensorEx;
extern ptrSimCheckProximitySensorEx2 simCheckProximitySensorEx2;
extern ptrSimCreateBuffer simCreateBuffer;
extern ptrSimReleaseBuffer simReleaseBuffer;
extern ptrSimCheckCollision simCheckCollision;
extern ptrSimCheckCollisionEx simCheckCollisionEx;
extern ptrSimCheckDistance simCheckDistance;
extern ptrSimSetSimulationTimeStep simSetSimulationTimeStep;
extern ptrSimGetSimulationTimeStep simGetSimulationTimeStep;
extern ptrSimGetRealTimeSimulation simGetRealTimeSimulation;
extern ptrSimIsRealTimeSimulationStepNeeded simIsRealTimeSimulationStepNeeded;
extern ptrSimAdjustRealTimeTimer simAdjustRealTimeTimer;
extern ptrSimGetSimulationPassesPerRenderingPass simGetSimulationPassesPerRenderingPass;
extern ptrSimAdvanceSimulationByOneStep simAdvanceSimulationByOneStep;
extern ptrSimStartSimulation simStartSimulation;
extern ptrSimStopSimulation simStopSimulation;
extern ptrSimPauseSimulation simPauseSimulation;
extern ptrSimGetModuleName simGetModuleName;
extern ptrSimFloatingViewAdd simFloatingViewAdd;
extern ptrSimFloatingViewRemove simFloatingViewRemove;
extern ptrSimAdjustView simAdjustView;
extern ptrSimSetLastError simSetLastError;
extern ptrSimHandleGraph simHandleGraph;
extern ptrSimResetGraph simResetGraph;
extern ptrSimAddGraphStream simAddGraphStream;
extern ptrSimDestroyGraphCurve simDestroyGraphCurve;
extern ptrSimSetGraphStreamTransformation simSetGraphStreamTransformation;
extern ptrSimDuplicateGraphCurveToStatic simDuplicateGraphCurveToStatic;
extern ptrSimAddGraphCurve simAddGraphCurve;
extern ptrSimSetGraphStreamValue simSetGraphStreamValue;
extern ptrSimSetNavigationMode simSetNavigationMode;
extern ptrSimGetNavigationMode simGetNavigationMode;
extern ptrSimSetPage simSetPage;
extern ptrSimGetPage simGetPage;
extern ptrSimRegisterScriptCallbackFunction simRegisterScriptCallbackFunction;
extern ptrSimRegisterScriptVariable simRegisterScriptVariable;
extern ptrSimRegisterScriptFuncHook simRegisterScriptFuncHook;
extern ptrSimSetJointTargetVelocity simSetJointTargetVelocity;
extern ptrSimGetJointTargetVelocity simGetJointTargetVelocity;
extern ptrSimCopyPasteObjects simCopyPasteObjects;
extern ptrSimScaleObjects simScaleObjects;
extern ptrSimAddDrawingObject simAddDrawingObject;
extern ptrSimRemoveDrawingObject simRemoveDrawingObject;
extern ptrSimAddDrawingObjectItem simAddDrawingObjectItem;
extern ptrSimGetObjectSizeFactor simGetObjectSizeFactor;
extern ptrSimAnnounceSceneContentChange simAnnounceSceneContentChange;
extern ptrSimSetInt32Signal simSetInt32Signal;
extern ptrSimGetInt32Signal simGetInt32Signal;
extern ptrSimClearInt32Signal simClearInt32Signal;
extern ptrSimSetFloatSignal simSetFloatSignal;
extern ptrSimGetFloatSignal simGetFloatSignal;
extern ptrSimClearFloatSignal simClearFloatSignal;
extern ptrSimSetStringSignal simSetStringSignal;
extern ptrSimGetStringSignal simGetStringSignal;
extern ptrSimClearStringSignal simClearStringSignal;
extern ptrSimGetSignalName simGetSignalName;
extern ptrSimSetObjectProperty simSetObjectProperty;
extern ptrSimGetObjectProperty simGetObjectProperty;
extern ptrSimSetObjectSpecialProperty simSetObjectSpecialProperty;
extern ptrSimGetObjectSpecialProperty simGetObjectSpecialProperty;
extern ptrSimReadForceSensor simReadForceSensor;
extern ptrSimSetLightParameters simSetLightParameters;
extern ptrSimGetLightParameters simGetLightParameters;
extern ptrSimGetVelocity simGetVelocity;
extern ptrSimGetObjectVelocity simGetObjectVelocity;
extern ptrSimGetJointVelocity simGetJointVelocity;
extern ptrSimAddForceAndTorque simAddForceAndTorque;
extern ptrSimAddForce simAddForce;
extern ptrSimSetExplicitHandling simSetExplicitHandling;
extern ptrSimGetExplicitHandling simGetExplicitHandling;
extern ptrSimGetLinkDummy simGetLinkDummy;
extern ptrSimSetLinkDummy simSetLinkDummy;
extern ptrSimSetModelProperty simSetModelProperty;
extern ptrSimGetModelProperty simGetModelProperty;
extern ptrSimSetObjectColor simSetObjectColor;
extern ptrSimGetObjectColor simGetObjectColor;
extern ptrSimSetShapeColor simSetShapeColor;
extern ptrSimGetShapeColor simGetShapeColor;
extern ptrSimResetDynamicObject simResetDynamicObject;
extern ptrSimSetJointMode simSetJointMode;
extern ptrSimGetJointMode simGetJointMode;
extern ptrSimSerialOpen simSerialOpen;
extern ptrSimSerialClose simSerialClose;
extern ptrSimSerialSend simSerialSend;
extern ptrSimSerialRead simSerialRead;
extern ptrSimSerialCheck simSerialCheck;
extern ptrSimGetContactInfo simGetContactInfo;
extern ptrSimAuxiliaryConsoleOpen simAuxiliaryConsoleOpen;
extern ptrSimAuxiliaryConsoleClose simAuxiliaryConsoleClose;
extern ptrSimAuxiliaryConsoleShow simAuxiliaryConsoleShow;
extern ptrSimAuxiliaryConsolePrint simAuxiliaryConsolePrint;
extern ptrSimImportShape simImportShape;
extern ptrSimImportMesh simImportMesh;
extern ptrSimExportMesh simExportMesh;
extern ptrSimCreateMeshShape simCreateMeshShape;
extern ptrSimCreatePrimitiveShape simCreatePrimitiveShape;
extern ptrSimCreateHeightfieldShape simCreateHeightfieldShape;
extern ptrSimGetShapeMesh simGetShapeMesh;
extern ptrSimCreateJoint simCreateJoint;
extern ptrSimCreateDummy simCreateDummy;
extern ptrSimCreateForceSensor simCreateForceSensor;
extern ptrSimCreateVisionSensor simCreateVisionSensor;
extern ptrSimCreateProximitySensor simCreateProximitySensor;
extern ptrSimGetObjectInt32Param simGetObjectInt32Param;
extern ptrSimSetObjectInt32Param simSetObjectInt32Param;
extern ptrSimGetObjectFloatParam simGetObjectFloatParam;
extern ptrSimSetObjectFloatParam simSetObjectFloatParam;
extern ptrSimGetObjectFloatArrayParam simGetObjectFloatArrayParam;
extern ptrSimSetObjectFloatArrayParam simSetObjectFloatArrayParam;
extern ptrSimGetObjectStringParam simGetObjectStringParam;
extern ptrSimSetObjectStringParam simSetObjectStringParam;
extern ptrSimSetSimulationPassesPerRenderingPass simSetSimulationPassesPerRenderingPass;
extern ptrSimGetRotationAxis simGetRotationAxis;
extern ptrSimRotateAroundAxis simRotateAroundAxis;
extern ptrSimGetJointForce simGetJointForce;
extern ptrSimGetJointTargetForce simGetJointTargetForce;
extern ptrSimSetJointTargetForce simSetJointTargetForce;
extern ptrSimCameraFitToView simCameraFitToView;
extern ptrSimPersistentDataWrite simPersistentDataWrite;
extern ptrSimPersistentDataRead simPersistentDataRead;
extern ptrSimIsHandle simIsHandle;
extern ptrSimHandleVisionSensor simHandleVisionSensor;
extern ptrSimReadVisionSensor simReadVisionSensor;
extern ptrSimResetVisionSensor simResetVisionSensor;
extern ptrSimCheckVisionSensor simCheckVisionSensor;
extern ptrSimCheckVisionSensorEx simCheckVisionSensorEx;
extern ptrSimGetVisionSensorImg simGetVisionSensorImg;
extern ptrSimSetVisionSensorImg simSetVisionSensorImg;
extern ptrSimGetVisionSensorDepth simGetVisionSensorDepth;
extern ptrSimGetObjectQuaternion simGetObjectQuaternion;
extern ptrSimSetObjectQuaternion simSetObjectQuaternion;
extern ptrSimRuckigPos simRuckigPos;
extern ptrSimRuckigVel simRuckigVel;
extern ptrSimRuckigStep simRuckigStep;
extern ptrSimRuckigRemove simRuckigRemove;
extern ptrSimGroupShapes simGroupShapes;
extern ptrSimUngroupShape simUngroupShape;
extern ptrSimConvexDecompose simConvexDecompose;
extern ptrSimQuitSimulator simQuitSimulator;
extern ptrSimSetShapeMaterial simSetShapeMaterial;
extern ptrSimGetTextureId simGetTextureId;
extern ptrSimReadTexture simReadTexture;
extern ptrSimWriteTexture simWriteTexture;
extern ptrSimCreateTexture simCreateTexture;
extern ptrSimWriteCustomDataBlock simWriteCustomDataBlock;
extern ptrSimReadCustomDataBlock simReadCustomDataBlock;
extern ptrSimReadCustomDataBlockTags simReadCustomDataBlockTags;
extern ptrSimGetShapeGeomInfo simGetShapeGeomInfo;
extern ptrSimGetObjects simGetObjects;
extern ptrSimGetObjectsInTree simGetObjectsInTree;
extern ptrSimScaleObject simScaleObject;
extern ptrSimSetShapeTexture simSetShapeTexture;
extern ptrSimGetShapeTextureId simGetShapeTextureId;
extern ptrSimCreateCollectionEx simCreateCollectionEx;
extern ptrSimAddItemToCollection simAddItemToCollection;
extern ptrSimDestroyCollection simDestroyCollection;
extern ptrSimGetCollectionObjects simGetCollectionObjects;
extern ptrSimGetScriptInt32Param simGetScriptInt32Param;
extern ptrSimSetScriptInt32Param simSetScriptInt32Param;
extern ptrSimGetScriptStringParam simGetScriptStringParam;
extern ptrSimSetScriptStringParam simSetScriptStringParam;
extern ptrSimReorientShapeBoundingBox simReorientShapeBoundingBox;
extern ptrSimSaveImage simSaveImage;
extern ptrSimLoadImage simLoadImage;
extern ptrSimGetScaledImage simGetScaledImage;
extern ptrSimTransformImage simTransformImage;
extern ptrSimGetQHull simGetQHull;
extern ptrSimGetDecimatedMesh simGetDecimatedMesh;
extern ptrSimCallScriptFunctionEx simCallScriptFunctionEx;
extern ptrSimGetExtensionString simGetExtensionString;
extern ptrSimComputeMassAndInertia simComputeMassAndInertia;
extern ptrSimCreateStack simCreateStack;
extern ptrSimReleaseStack simReleaseStack;
extern ptrSimCopyStack simCopyStack;
extern ptrSimPushNullOntoStack simPushNullOntoStack;
extern ptrSimPushBoolOntoStack simPushBoolOntoStack;
extern ptrSimPushInt32OntoStack simPushInt32OntoStack;
extern ptrSimPushInt64OntoStack simPushInt64OntoStack;
extern ptrSimPushFloatOntoStack simPushFloatOntoStack;
extern ptrSimPushDoubleOntoStack simPushDoubleOntoStack;
extern ptrSimPushStringOntoStack simPushStringOntoStack;
extern ptrSimPushUInt8TableOntoStack simPushUInt8TableOntoStack;
extern ptrSimPushInt32TableOntoStack simPushInt32TableOntoStack;
extern ptrSimPushInt64TableOntoStack simPushInt64TableOntoStack;
extern ptrSimPushFloatTableOntoStack simPushFloatTableOntoStack;
extern ptrSimPushDoubleTableOntoStack simPushDoubleTableOntoStack;
extern ptrSimPushTableOntoStack simPushTableOntoStack;
extern ptrSimInsertDataIntoStackTable simInsertDataIntoStackTable;
extern ptrSimGetStackSize simGetStackSize;
extern ptrSimPopStackItem simPopStackItem;
extern ptrSimMoveStackItemToTop simMoveStackItemToTop;
extern ptrSimIsStackValueNull simIsStackValueNull;
extern ptrSimGetStackBoolValue simGetStackBoolValue;
extern ptrSimGetStackInt32Value simGetStackInt32Value;
extern ptrSimGetStackInt64Value simGetStackInt64Value;
extern ptrSimGetStackFloatValue simGetStackFloatValue;
extern ptrSimGetStackDoubleValue simGetStackDoubleValue;
extern ptrSimGetStackStringValue simGetStackStringValue;
extern ptrSimGetStackTableInfo simGetStackTableInfo;
extern ptrSimGetStackUInt8Table simGetStackUInt8Table;
extern ptrSimGetStackInt32Table simGetStackInt32Table;
extern ptrSimGetStackInt64Table simGetStackInt64Table;
extern ptrSimGetStackFloatTable simGetStackFloatTable;
extern ptrSimGetStackDoubleTable simGetStackDoubleTable;
extern ptrSimUnfoldStackTable simUnfoldStackTable;
extern ptrSimDebugStack simDebugStack;
extern ptrSimGetEngineFloatParam simGetEngineFloatParam;
extern ptrSimGetEngineInt32Param simGetEngineInt32Param;
extern ptrSimGetEngineBoolParam simGetEngineBoolParam;
extern ptrSimSetEngineFloatParam simSetEngineFloatParam;
extern ptrSimSetEngineInt32Param simSetEngineInt32Param;
extern ptrSimSetEngineBoolParam simSetEngineBoolParam;
extern ptrSimCreateOctree simCreateOctree;
extern ptrSimCreatePointCloud simCreatePointCloud;
extern ptrSimSetPointCloudOptions simSetPointCloudOptions;
extern ptrSimGetPointCloudOptions simGetPointCloudOptions;
extern ptrSimInsertVoxelsIntoOctree simInsertVoxelsIntoOctree;
extern ptrSimRemoveVoxelsFromOctree simRemoveVoxelsFromOctree;
extern ptrSimInsertPointsIntoPointCloud simInsertPointsIntoPointCloud;
extern ptrSimRemovePointsFromPointCloud simRemovePointsFromPointCloud;
extern ptrSimIntersectPointsWithPointCloud simIntersectPointsWithPointCloud;
extern ptrSimGetOctreeVoxels simGetOctreeVoxels;
extern ptrSimGetPointCloudPoints simGetPointCloudPoints;
extern ptrSimInsertObjectIntoOctree simInsertObjectIntoOctree;
extern ptrSimSubtractObjectFromOctree simSubtractObjectFromOctree;
extern ptrSimInsertObjectIntoPointCloud simInsertObjectIntoPointCloud;
extern ptrSimSubtractObjectFromPointCloud simSubtractObjectFromPointCloud;
extern ptrSimCheckOctreePointOccupancy simCheckOctreePointOccupancy;
extern ptrSimOpenTextEditor simOpenTextEditor;
extern ptrSimPackTable simPackTable;
extern ptrSimUnpackTable simUnpackTable;
extern ptrSimSetReferencedHandles simSetReferencedHandles;
extern ptrSimGetReferencedHandles simGetReferencedHandles;
extern ptrSimGetShapeViz simGetShapeViz;
extern ptrSimExecuteScriptString simExecuteScriptString;
extern ptrSimGetApiFunc simGetApiFunc;
extern ptrSimGetApiInfo simGetApiInfo;
extern ptrSimSetModuleInfo simSetModuleInfo;
extern ptrSimGetModuleInfo simGetModuleInfo;
extern ptrSimIsDeprecated simIsDeprecated;
extern ptrSimGetPersistentDataTags simGetPersistentDataTags;
extern ptrSimEventNotification simEventNotification;
extern ptrSimApplyTexture simApplyTexture;
extern ptrSimSetJointDependency simSetJointDependency;
extern ptrSimGetJointDependency simGetJointDependency;
extern ptrSimAddLog simAddLog;
extern ptrSimGetShapeMass simGetShapeMass;
extern ptrSimSetShapeMass simSetShapeMass;
extern ptrSimGetShapeInertia simGetShapeInertia;
extern ptrSimSetShapeInertia simSetShapeInertia;
extern ptrSimIsDynamicallyEnabled simIsDynamicallyEnabled;
extern ptrSimGenerateShapeFromPath simGenerateShapeFromPath;
extern ptrSimGetClosestPosOnPath simGetClosestPosOnPath;
extern ptrSimInitScript simInitScript;
extern ptrSimModuleEntry simModuleEntry;
extern ptrSimCheckExecAuthorization simCheckExecAuthorization;


/* Following courtesy of Stephen James: */
extern ptrSimExtLaunchUIThread simExtLaunchUIThread;
extern ptrSimExtCanInitSimThread simExtCanInitSimThread;
extern ptrSimExtSimThreadInit simExtSimThreadInit;
extern ptrSimExtSimThreadDestroy simExtSimThreadDestroy;
extern ptrSimExtPostExitRequest simExtPostExitRequest;
extern ptrSimExtGetExitRequest simExtGetExitRequest;
extern ptrSimExtStep simExtStep;
extern ptrSimExtCallScriptFunction simExtCallScriptFunction;

extern ptr_simSetDynamicSimulationIconCode _simSetDynamicSimulationIconCode;
extern ptr_simSetDynamicObjectFlagForVisualization _simSetDynamicObjectFlagForVisualization;
extern ptr_simGetObjectListSize _simGetObjectListSize;
extern ptr_simGetObjectFromIndex _simGetObjectFromIndex;
extern ptr_simGetObjectID _simGetObjectID;
extern ptr_simGetObjectType _simGetObjectType;
extern ptr_simGetObjectChildren _simGetObjectChildren;
extern ptr_simGetGeomProxyFromShape _simGetGeomProxyFromShape;
extern ptr_simGetParentObject _simGetParentObject;
extern ptr_simGetObject _simGetObject;
extern ptr_simGetIkGroupObject _simGetIkGroupObject;
extern ptr_simMpHandleIkGroupObject _simMpHandleIkGroupObject;
extern ptr_simGetObjectLocalTransformation _simGetObjectLocalTransformation;
extern ptr_simSetObjectLocalTransformation _simSetObjectLocalTransformation;
extern ptr_simDynReportObjectCumulativeTransformation _simDynReportObjectCumulativeTransformation;
extern ptr_simSetObjectCumulativeTransformation _simSetObjectCumulativeTransformation;
extern ptr_simGetObjectCumulativeTransformation _simGetObjectCumulativeTransformation;
extern ptr_simIsShapeDynamicallyStatic _simIsShapeDynamicallyStatic;
extern ptr_simGetTreeDynamicProperty _simGetTreeDynamicProperty;
extern ptr_simGetDummyLinkType _simGetDummyLinkType;
extern ptr_simGetJointMode _simGetJointMode;
extern ptr_simIsJointInHybridOperation _simIsJointInHybridOperation;
extern ptr_simDisableDynamicTreeForManipulation _simDisableDynamicTreeForManipulation;
extern ptr_simIsShapeDynamicallyRespondable _simIsShapeDynamicallyRespondable;
extern ptr_simGetDynamicCollisionMask _simGetDynamicCollisionMask;
extern ptr_simGetLastParentForLocalGlobalCollidable _simGetLastParentForLocalGlobalCollidable;
extern ptr_simSetJointVelocity _simSetJointVelocity;
extern ptr_simSetJointPosition _simSetJointPosition;
extern ptr_simGetJointPosition _simGetJointPosition;
extern ptr_simSetDynamicMotorPositionControlTargetPosition _simSetDynamicMotorPositionControlTargetPosition;
extern ptr_simGetInitialDynamicVelocity _simGetInitialDynamicVelocity;
extern ptr_simSetInitialDynamicVelocity _simSetInitialDynamicVelocity;
extern ptr_simGetInitialDynamicAngVelocity _simGetInitialDynamicAngVelocity;
extern ptr_simSetInitialDynamicAngVelocity _simSetInitialDynamicAngVelocity;
extern ptr_simGetStartSleeping _simGetStartSleeping;
extern ptr_simGetWasPutToSleepOnce _simGetWasPutToSleepOnce;
extern ptr_simGetDynamicsFullRefreshFlag _simGetDynamicsFullRefreshFlag;
extern ptr_simSetDynamicsFullRefreshFlag _simSetDynamicsFullRefreshFlag;
extern ptr_simSetShapeDynamicVelocity _simSetShapeDynamicVelocity;
extern ptr_simGetAdditionalForceAndTorque _simGetAdditionalForceAndTorque;
extern ptr_simClearAdditionalForceAndTorque _simClearAdditionalForceAndTorque;
extern ptr_simGetJointPositionInterval _simGetJointPositionInterval;
extern ptr_simGetJointType _simGetJointType;
extern ptr_simGetDynamicMotorTargetPosition _simGetDynamicMotorTargetPosition;
extern ptr_simGetDynamicMotorTargetVelocity _simGetDynamicMotorTargetVelocity;
extern ptr_simGetDynamicMotorMaxForce _simGetDynamicMotorMaxForce;
extern ptr_simGetDynamicMotorUpperLimitVelocity _simGetDynamicMotorUpperLimitVelocity;
extern ptr_simSetDynamicMotorReflectedPositionFromDynamicEngine _simSetDynamicMotorReflectedPositionFromDynamicEngine;
extern ptr_simSetJointSphericalTransformation _simSetJointSphericalTransformation;
extern ptr_simAddForceSensorCumulativeForcesAndTorques _simAddForceSensorCumulativeForcesAndTorques;
extern ptr_simAddJointCumulativeForcesOrTorques _simAddJointCumulativeForcesOrTorques;
extern ptr_simGetGeomWrapFromGeomProxy _simGetGeomWrapFromGeomProxy;
extern ptr_simGetPurePrimitiveType _simGetPurePrimitiveType;
extern ptr_simIsGeomWrapGeometric _simIsGeomWrapGeometric;
extern ptr_simIsGeomWrapConvex _simIsGeomWrapConvex;
extern ptr_simGetGeometricCount _simGetGeometricCount;
extern ptr_simGetAllGeometrics _simGetAllGeometrics;
extern ptr_simGetPurePrimitiveSizes _simGetPurePrimitiveSizes;
extern ptr_simMakeDynamicAnnouncement _simMakeDynamicAnnouncement;
extern ptr_simGetVerticesLocalFrame _simGetVerticesLocalFrame;
extern ptr_simGetHeightfieldData _simGetHeightfieldData;
extern ptr_simGetCumulativeMeshes _simGetCumulativeMeshes;
extern ptr_simGetMass _simGetMass;
extern ptr_simGetLocalInertiaInfo _simGetLocalInertiaInfo;
extern ptr_simGetGravity _simGetGravity;
extern ptr_simGetTimeDiffInMs _simGetTimeDiffInMs;
extern ptr_simDoEntitiesCollide _simDoEntitiesCollide;
extern ptr_simGetDistanceBetweenEntitiesIfSmaller _simGetDistanceBetweenEntitiesIfSmaller;
extern ptr_simHandleJointControl _simHandleJointControl;
extern ptr_simHandleCustomContact _simHandleCustomContact;
extern ptr_simGetPureHollowScaling _simGetPureHollowScaling;
extern ptr_simGetJointDynCtrlMode _simGetJointDynCtrlMode;
extern ptr_simDynCallback _simDynCallback;

#include "simLib-old.h"
#endif
