// Use this header to dynamically load and bind coppeliaSim.dll and its functions (call loadSimLibrary and unloadSimLibrary)

#if !defined(SIMLIB_INCLUDED_)
#define SIMLIB_INCLUDED_

#include "simConst.h"
#include "simTypes.h"
#ifdef SIM_INTERFACE_SINGLE
#define SIMDOUBLE float
#else
#define SIMDOUBLE double
#endif

#ifdef SIM_UNIFIED_HANDLES
#define SIMHANDLE long long int
#define LH true
#else
#define SIMHANDLE int
#define LH false
#endif

#ifdef QT_FRAMEWORK
    #include <QLibrary>
    #include <QDebug>
    #define LIBRARY QLibrary*
    #define __cdecl
    #define FARPROC void*
#else
    #ifdef _WIN32
        #include <Windows.h>
        #define LIBRARY HINSTANCE
    #elif defined (__linux) || defined (__APPLE__)
        #define __cdecl
        #define FARPROC void*
        #define LIBRARY void*
    #endif
    #include <stdio.h>
#endif // QT_FRAMEWORK

int getSimProcAddresses(LIBRARY lib);
LIBRARY loadSimLibrary(const char* pathAndFilename);
void unloadSimLibrary(LIBRARY lib);
FARPROC _getProcAddress(LIBRARY lib,const char* funcName);
int simAddLog(const char* pluginName,int verbosityLevel,const char* logMsg);


typedef int (__cdecl *ptrSimSetBoolProperty)(long long int target, const char* pName, int pState);
typedef int (__cdecl *ptrSimGetBoolProperty)(long long int target, const char* pName, int* pState);
typedef int (__cdecl *ptrSimSetIntProperty)(long long int target, const char* pName, int pState);
typedef int (__cdecl *ptrSimGetIntProperty)(long long int target, const char* pName, int* pState);
typedef int (__cdecl *ptrSimSetLongProperty)(long long int target, const char* pName, long long int pState);
typedef int (__cdecl *ptrSimGetLongProperty)(long long int target, const char* pName, long long int* pState);
typedef int (__cdecl *ptrSimSetFloatProperty)(long long int target, const char* pName, double pState);
typedef int (__cdecl *ptrSimGetFloatProperty)(long long int target, const char* pName, double* pState);
typedef int (__cdecl *ptrSimSetStringProperty)(long long int target, const char* pName, const char* pState);
typedef char* (__cdecl *ptrSimGetStringProperty)(long long int target, const char* pName);
typedef int (__cdecl *ptrSimSetTableProperty)(long long int target, const char* pName, const char* buffer, int bufferL);
typedef char* (__cdecl *ptrSimGetTableProperty)(long long int target, const char* pName, int* bufferL);
typedef int (__cdecl *ptrSimSetBufferProperty)(long long int target, const char* pName, const char* buffer, int bufferL);
typedef char* (__cdecl *ptrSimGetBufferProperty)(long long int target, const char* pName, int* bufferL);
typedef int (__cdecl *ptrSimSetIntArray2Property)(long long int target, const char* pName, const int* pState);
typedef int (__cdecl *ptrSimGetIntArray2Property)(long long int target, const char* pName, int* pState);
typedef int (__cdecl *ptrSimSetVector2Property)(long long int target, const char* pName, const double* pState);
typedef int (__cdecl *ptrSimGetVector2Property)(long long int target, const char* pName, double* pState);
typedef int (__cdecl *ptrSimSetVector3Property)(long long int target, const char* pName, const double* pState);
typedef int (__cdecl *ptrSimGetVector3Property)(long long int target, const char* pName, double* pState);
typedef int (__cdecl *ptrSimSetQuaternionProperty)(long long int target, const char* pName, const double* pState);
typedef int (__cdecl *ptrSimGetQuaternionProperty)(long long int target, const char* pName, double* pState);
typedef int (__cdecl *ptrSimSetPoseProperty)(long long int target, const char* pName, const double* pState);
typedef int (__cdecl *ptrSimGetPoseProperty)(long long int target, const char* pName, double* pState);
typedef int (__cdecl *ptrSimSetColorProperty)(long long int target, const char* pName, const float* pState);
typedef int (__cdecl *ptrSimGetColorProperty)(long long int target, const char* pName, float* pState);
typedef int (__cdecl *ptrSimSetFloatArrayProperty)(long long int target, const char* pName, const double* v, int vL);
typedef double* (__cdecl *ptrSimGetFloatArrayProperty)(long long int target, const char* pName, int* vL);
typedef int (__cdecl *ptrSimSetIntArrayProperty)(long long int target, const char* pName, const int* v, int vL);
typedef int* (__cdecl *ptrSimGetIntArrayProperty)(long long int target, const char* pName, int* vL);
typedef int (__cdecl *ptrSimRemoveProperty)(long long int target, const char* pName);
typedef char* (__cdecl *ptrSimGetPropertyName)(long long int target, int index, SPropertyOptions* options);
typedef int (__cdecl *ptrSimGetPropertyInfo)(long long int target, const char* pName, SPropertyInfo* infos, SPropertyOptions* options);

typedef void (__cdecl *ptrSimRegCallback)(int index, void* cb);
typedef void (__cdecl *ptrSimRunGui)(int options);
typedef int (__cdecl *ptrSimInitialize)(const char* appDir,int options);
typedef int (__cdecl *ptrSimDeinitialize)();
typedef int (__cdecl *ptrSimPostExitRequest)();
typedef int (__cdecl *ptrSimGetExitRequest)();
typedef int (__cdecl *ptrSimLoop)(void(*callback)(),int options);
typedef int (__cdecl *ptrSimTest)(int mode,void* ptr1,void* ptr2,void* ptr3);
typedef int (__cdecl *ptrSimAddLog)(const char* pluginName,int verbosityLevel,const char* logMsg);
typedef char* (__cdecl *ptrSimGetSimulatorMessage)(int* messageID,int* auxiliaryData,int* returnedDataSize);
typedef void* (__cdecl *ptrSimGetMainWindow)(int type);
typedef char* (__cdecl *ptrSimGetLastError)();
typedef char* (__cdecl *ptrSimGetLastInfo)();
typedef SIMHANDLE (__cdecl *ptrSimGetObject)(const char* objectPath,int index,SIMHANDLE proxy,int options);
typedef long long int (__cdecl *ptrSimGetObjectUid)(SIMHANDLE objectHandle);
typedef SIMHANDLE (__cdecl *ptrSimGetObjectFromUid)(long long int uid,int options);
typedef SIMHANDLE (__cdecl *ptrSimGetScriptHandleEx)(int scriptType,SIMHANDLE objHandle,const char* scriptName);
typedef int (__cdecl *ptrSimRemoveObjects)(const SIMHANDLE* objectHandles,int count);
typedef int (__cdecl *ptrSimRemoveModel)(SIMHANDLE objectHandle);
typedef char* (__cdecl *ptrSimGetObjectAlias)(SIMHANDLE objectHandle,int options);
typedef int (__cdecl *ptrSimSetObjectAlias)(SIMHANDLE objectHandle,const char* objectAlias,int options);
typedef SIMHANDLE (__cdecl *ptrSimGetObjectParent)(SIMHANDLE objectHandle);
typedef SIMHANDLE (__cdecl *ptrSimGetObjectChild)(SIMHANDLE objectHandle,int index);
typedef int (__cdecl *ptrSimSetObjectParent)(SIMHANDLE objectHandle,SIMHANDLE parentObjectHandle,bool keepInPlace);
typedef int (__cdecl *ptrSimGetObjectType)(SIMHANDLE objectHandle);
typedef int (__cdecl *ptrSimGetJointType)(SIMHANDLE objectHandle);
typedef int (__cdecl *ptrSimReservedCommand)(int v,int w);
typedef int (__cdecl *ptrSimGetSimulationState)();
typedef int (__cdecl *ptrSimLoadScene)(const char* filename);
typedef int (__cdecl *ptrSimCloseScene)();
typedef int (__cdecl *ptrSimSaveScene)(const char* filename);
typedef SIMHANDLE (__cdecl *ptrSimLoadModel)(const char* filename);
typedef int (__cdecl *ptrSimSaveModel)(SIMHANDLE baseOfModelHandle,const char* filename);
typedef int (__cdecl *ptrSimDoesFileExist)(const char* filename);
typedef SIMHANDLE* (__cdecl *ptrSimGetObjectSel)(int* cnt);
typedef int (__cdecl *ptrSimSetObjectSel)(const SIMHANDLE* handles,int cnt);
typedef int (__cdecl *ptrSimResetScript)(SIMHANDLE scriptHandle);
typedef int (__cdecl *ptrSimRefreshDialogs)(int refreshDegree);
typedef int (__cdecl *ptrSimResetProximitySensor)(SIMHANDLE sensorHandle);
typedef void* (__cdecl *ptrSimCreateBuffer)(int size);
typedef int (__cdecl *ptrSimReleaseBuffer)(const void* buffer);
typedef int (__cdecl *ptrSimCheckCollision)(SIMHANDLE entity1Handle,SIMHANDLE entity2Handle);
typedef int (__cdecl *ptrSimGetRealTimeSimulation)();
typedef int (__cdecl *ptrSimStartSimulation)();
typedef int (__cdecl *ptrSimStopSimulation)();
typedef int (__cdecl *ptrSimPauseSimulation)();
typedef int (__cdecl *ptrSimAdjustView)(int viewHandleOrIndex,SIMHANDLE associatedViewableObjectHandle,int options,const char* viewLabel);
typedef int (__cdecl *ptrSimSetLastError)(const char* setToNullptr,const char* errorMessage);
typedef int (__cdecl *ptrSimResetGraph)(SIMHANDLE graphHandle);
typedef int (__cdecl *ptrSimDestroyGraphCurve)(SIMHANDLE graphHandle,SIMHANDLE curveId);
typedef int (__cdecl *ptrSimDuplicateGraphCurveToStatic)(SIMHANDLE graphHandle,SIMHANDLE curveId,const char* curveName);
typedef int (__cdecl *ptrSimSetNavigationMode)(int navigationMode);
typedef int (__cdecl *ptrSimGetNavigationMode)();
typedef int (__cdecl *ptrSimSetPage)(int index);
typedef int (__cdecl *ptrSimGetPage)();
typedef int (__cdecl *ptrSimRegisterScriptCallbackFunction)(const char* func,const char* reserved_setToNull,void(*callBack)(struct SScriptCallBack* cb));
typedef int (__cdecl *ptrSimRegisterScriptVariable)(const char* var,const char* value,SIMHANDLE stackHandle);
typedef int (__cdecl *ptrSimRegisterScriptFuncHook)(SIMHANDLE scriptHandle,const char* funcToHook,const char* userFunction,bool executeBefore,int options);
typedef int (__cdecl *ptrSimCopyPasteObjects)(SIMHANDLE* objectHandles,int objectCount,int options);
typedef int (__cdecl *ptrSimRemoveDrawingObject)(SIMHANDLE objectHandle);
typedef int (__cdecl *ptrSimAnnounceSceneContentChange)();
typedef int (__cdecl *ptrSimSetExplicitHandling)(SIMHANDLE objectHandle,int explicitFlags);
typedef int (__cdecl *ptrSimGetExplicitHandling)(SIMHANDLE objectHandle);
typedef SIMHANDLE (__cdecl *ptrSimGetLinkDummy)(SIMHANDLE dummyHandle);
typedef int (__cdecl *ptrSimSetLinkDummy)(SIMHANDLE dummyHandle,SIMHANDLE linkedDummyHandle);
typedef int (__cdecl *ptrSimResetDynamicObject)(SIMHANDLE objectHandle);
typedef int (__cdecl *ptrSimSetJointMode)(SIMHANDLE jointHandle,int jointMode,int options);
typedef int (__cdecl *ptrSimGetJointMode)(SIMHANDLE jointHandle,int* options);
typedef int (__cdecl *ptrSimSerialOpen)(const char* portString,int baudRate,void* reserved1,void* reserved2);
typedef int (__cdecl *ptrSimSerialClose)(int portHandle);
typedef int (__cdecl *ptrSimSerialSend)(int portHandle,const char* data,int dataLength);
typedef int (__cdecl *ptrSimSerialRead)(int portHandle,char* buffer,int dataLengthToRead);
typedef int (__cdecl *ptrSimSerialCheck)(int portHandle);
typedef int (__cdecl *ptrSimAuxiliaryConsoleClose)(int consoleHandle);
typedef int (__cdecl *ptrSimAuxiliaryConsoleShow)(int consoleHandle,bool showState);
typedef int (__cdecl *ptrSimAuxiliaryConsolePrint)(int consoleHandle,const char* text);
typedef int (__cdecl *ptrSimIsHandle)(SIMHANDLE generalObjectHandle,int generalObjectType);
typedef int (__cdecl *ptrSimResetVisionSensor)(SIMHANDLE visionSensorHandle);
typedef int (__cdecl *ptrSimSetVisionSensorImg)(SIMHANDLE sensorHandle,const unsigned char* img,int options,const int* pos,const int* size);
typedef int (__cdecl *ptrSimRuckigRemove)(int objHandle);
typedef SIMHANDLE (__cdecl *ptrSimGroupShapes)(const SIMHANDLE* shapeHandles,int shapeCount);
typedef SIMHANDLE* (__cdecl *ptrSimUngroupShape)(SIMHANDLE shapeHandle,int* shapeCount);
typedef void (__cdecl *ptrSimQuitSimulator)(bool ignoredArgument);
typedef int (__cdecl *ptrSimSetShapeMaterial)(SIMHANDLE shapeHandle,SIMHANDLE materialIdOrShapeHandle);
typedef SIMHANDLE (__cdecl *ptrSimGetTextureId)(const char* textureName,int* resolution);
typedef unsigned char* (__cdecl *ptrSimReadTexture)(SIMHANDLE textureId,int options,int posX,int posY,int sizeX,int sizeY);
typedef SIMHANDLE (__cdecl *ptrSimGetObjects)(int index,int objectType);
typedef SIMHANDLE* (__cdecl *ptrSimGetObjectsInTree)(SIMHANDLE treeBaseHandle,int objectType,int options,int* objectCount);
typedef SIMHANDLE (__cdecl *ptrSimGetShapeTextureId)(SIMHANDLE shapeHandle);
typedef SIMHANDLE (__cdecl *ptrSimCreateCollectionEx)(int options);
typedef int (__cdecl *ptrSimAddItemToCollection)(SIMHANDLE collectionHandle,int what,SIMHANDLE objectHandle,int options);
typedef int (__cdecl *ptrSimDestroyCollection)(SIMHANDLE collectionHandle);
typedef SIMHANDLE* (__cdecl *ptrSimGetCollectionObjects)(SIMHANDLE collectionHandle,int* objectCount);
typedef int (__cdecl *ptrSimAlignShapeBB)(SIMHANDLE shapeHandle,const double* pose);
typedef int (__cdecl *ptrSimRelocateShapeFrame)(SIMHANDLE shapeHandle,const double* pose);
typedef int (__cdecl *ptrSimSaveImage)(const unsigned char* image,const int* resolution,int options,const char* filename,int quality,void* reserved);
typedef unsigned char* (__cdecl *ptrSimLoadImage)(int* resolution,int options,const char* filename,void* reserved);
typedef unsigned char* (__cdecl *ptrSimGetScaledImage)(const unsigned char* imageIn,const int* resolutionIn,int* resolutionOut,int options,void* reserved);
typedef int (__cdecl *ptrSimCallScriptFunctionEx)(SIMHANDLE scriptHandleOrType,const char* functionNameAtScriptName,SIMHANDLE stackId);
typedef char* (__cdecl *ptrSimGetExtensionString)(SIMHANDLE objectHandle,int index,const char* key);
typedef SIMHANDLE (__cdecl *ptrSimCreateStack)();
typedef int (__cdecl *ptrSimReleaseStack)(SIMHANDLE stackHandle);
typedef SIMHANDLE (__cdecl *ptrSimCopyStack)(SIMHANDLE stackHandle);
typedef int (__cdecl *ptrSimPushNullOntoStack)(SIMHANDLE stackHandle);
typedef int (__cdecl *ptrSimPushBoolOntoStack)(SIMHANDLE stackHandle,bool value);
typedef int (__cdecl *ptrSimPushInt32OntoStack)(SIMHANDLE stackHandle,int value);
typedef int (__cdecl *ptrSimPushInt64OntoStack)(SIMHANDLE stackHandle,long long int value);
typedef int (__cdecl *ptrSimPushTextOntoStack)(SIMHANDLE stackHandle,const char* value);
typedef int (__cdecl *ptrSimPushStringOntoStack)(SIMHANDLE stackHandle,const char* value,int stringSize);
typedef int (__cdecl *ptrSimPushBufferOntoStack)(SIMHANDLE stackHandle,const char* value,int stringSize);
typedef int (__cdecl *ptrSimPushUInt8TableOntoStack)(SIMHANDLE stackHandle,const unsigned char* values,int valueCnt);
typedef int (__cdecl *ptrSimPushInt32TableOntoStack)(SIMHANDLE stackHandle,const int* values,int valueCnt);
typedef int (__cdecl *ptrSimPushInt64TableOntoStack)(SIMHANDLE stackHandle,const long long int* values,int valueCnt);
typedef int (__cdecl *ptrSimPushTableOntoStack)(SIMHANDLE stackHandle);
typedef int (__cdecl *ptrSimInsertDataIntoStackTable)(SIMHANDLE stackHandle);
typedef int (__cdecl *ptrSimGetStackSize)(SIMHANDLE stackHandle);
typedef int (__cdecl *ptrSimPopStackItem)(SIMHANDLE stackHandle,int count);
typedef int (__cdecl *ptrSimMoveStackItemToTop)(SIMHANDLE stackHandle,int cIndex);
typedef int (__cdecl *ptrSimGetStackItemType)(SIMHANDLE stackHandle,int cIndex);
typedef int (__cdecl *ptrSimGetStackStringType)(SIMHANDLE stackHandle,int cIndex);
typedef int (__cdecl *ptrSimGetStackBoolValue)(SIMHANDLE stackHandle,bool* boolValue);
typedef int (__cdecl *ptrSimGetStackInt32Value)(SIMHANDLE stackHandle,int* numberValue);
typedef int (__cdecl *ptrSimGetStackInt64Value)(SIMHANDLE stackHandle,long long int* numberValue);
typedef char* (__cdecl *ptrSimGetStackStringValue)(SIMHANDLE stackHandle,int* stringSize);
typedef int (__cdecl *ptrSimGetStackTableInfo)(SIMHANDLE stackHandle,int infoType);
typedef int (__cdecl *ptrSimGetStackUInt8Table)(SIMHANDLE stackHandle,unsigned char* array,int count);
typedef int (__cdecl *ptrSimGetStackInt32Table)(SIMHANDLE stackHandle,int* array,int count);
typedef int (__cdecl *ptrSimGetStackInt64Table)(SIMHANDLE stackHandle,long long int* array,int count);
typedef int (__cdecl *ptrSimUnfoldStackTable)(SIMHANDLE stackHandle);
typedef int (__cdecl *ptrSimDebugStack)(SIMHANDLE stackHandle,int cIndex);
typedef int (__cdecl *ptrSimInsertObjectIntoOctree)(SIMHANDLE octreeHandle,SIMHANDLE objectHandle,int options,const unsigned char* color,unsigned int tag,void* reserved);
typedef int (__cdecl *ptrSimSubtractObjectFromOctree)(SIMHANDLE octreeHandle,SIMHANDLE objectHandle,int options,void* reserved);
typedef char* (__cdecl *ptrSimOpenTextEditor)(const char* initText,const char* xml,int* various);
typedef char* (__cdecl *ptrSimPackTable)(SIMHANDLE stackHandle,int* bufferSize);
typedef int (__cdecl *ptrSimUnpackTable)(SIMHANDLE stackHandle,const char* buffer,int bufferSize);
typedef int (__cdecl *ptrSimSetReferencedHandles)(SIMHANDLE objectHandle,int count,const SIMHANDLE* referencedHandles,const char* tag,const int* reserved2);
typedef int (__cdecl *ptrSimGetReferencedHandles)(SIMHANDLE objectHandle,SIMHANDLE** referencedHandles,const char* tag,SIMHANDLE** reserved2);
typedef int (__cdecl *ptrSimExecuteScriptString)(SIMHANDLE scriptHandle,const char* stringToExecute,SIMHANDLE stackHandle);
typedef char* (__cdecl *ptrSimGetApiFunc)(SIMHANDLE scriptHandle,const char* apiWord);
typedef char* (__cdecl *ptrSimGetApiInfo)(SIMHANDLE scriptHandle,const char* apiWord);
typedef int (__cdecl *ptrSimSetPluginInfo)(const char* pluginName,int infoType,const char* stringInfo,int intInfo);
typedef int (__cdecl *ptrSimGetPluginInfo)(const char* pluginName,int infoType,char** stringInfo,int* intInfo);
typedef char* (__cdecl *ptrSimGetPluginName)(int index);
typedef int (__cdecl *ptrSimEventNotification)(const char* event);
typedef int (__cdecl *ptrSimIsDynamicallyEnabled)(SIMHANDLE objectHandle);
typedef int (__cdecl *ptrSimInitScript)(SIMHANDLE scriptHandle);
typedef int (__cdecl *ptrSimModuleEntry)(int handle,const char* label,int state);
typedef int (__cdecl *ptrSimCheckExecAuthorization)(const char* what,const char* args);
/* ------------------------------------------------------- */
typedef int (__cdecl *ptrSimPushFloatOntoStack)(SIMHANDLE stackHandle,float value);
typedef int (__cdecl *ptrSimPushFloatTableOntoStack)(SIMHANDLE stackHandle,const float* values,int valueCnt);
typedef int (__cdecl *ptrSimGetStackFloatValue)(SIMHANDLE stackHandle,float* numberValue);
typedef int (__cdecl *ptrSimGetStackFloatTable)(SIMHANDLE stackHandle,float* array,int count);
typedef float* (__cdecl *ptrSimGetVisionSensorDepth)(SIMHANDLE sensorHandle,int options,const int* pos,const int* size,int* resolution);
typedef int (__cdecl *ptr_simSetVisionSensorDepth)(SIMHANDLE sensorHandle,int options,const float* depth);
typedef float* (__cdecl *ptrSimCheckVisionSensorEx)(SIMHANDLE visionSensorHandle,SIMHANDLE entityHandle,bool returnImage);
/* ------------------------------------------------------- */
typedef int (__cdecl *ptrSimRuckigPos)(int dofs,double baseCycleTime,int flags,const double* currentPos,const double* currentVel,const double* currentAccel,const double* maxVel,const double* maxAccel,const double* maxJerk,const bool* selection,const double* targetPos,const double* targetVel,double* reserved1,int* reserved2);
typedef int (__cdecl *ptrSimRuckigVel)(int dofs,double baseCycleTime,int flags,const double* currentPos,const double* currentVel,const double* currentAccel,const double* maxAccel,const double* maxJerk,const bool* selection,const double* targetVel,double* reserved1,int* reserved2);
typedef int (__cdecl *ptrSimRuckigStep)(int objHandle,double cycleTime,double* newPos,double* newVel,double* newAccel,double* syncTime,double* reserved1,int* reserved2);
typedef int (__cdecl *ptrSimPushDoubleOntoStack)(SIMHANDLE stackHandle,double value);
typedef int (__cdecl *ptrSimPushDoubleTableOntoStack)(SIMHANDLE stackHandle,const double* values,int valueCnt);
typedef int (__cdecl *ptrSimGetStackDoubleValue)(SIMHANDLE stackHandle,double* numberValue);
typedef int (__cdecl *ptrSimGetStackDoubleTable)(SIMHANDLE stackHandle,double* array,int count);
/* non-documented functions, mainly for the dynamics plugins: */
typedef void (__cdecl *ptr_simSetDynamicSimulationIconCode)(void* object,int code);
typedef void (__cdecl *ptr_simSetDynamicObjectFlagForVisualization)(void* object,int flag);
typedef int (__cdecl *ptr_simGetObjectListSize)(int objType);
typedef const void* (__cdecl *ptr_simGetObjectFromIndex)(int objType,int index);
typedef SIMHANDLE (__cdecl *ptr_simGetObjectID)(const void* object);
typedef int (__cdecl *ptr_simGetObjectType)(const void* object);
typedef const void** (__cdecl *ptr_simGetObjectChildren)(const void* object,int* count);
typedef const void* (__cdecl *ptr_simGetParentObject)(const void* object);
typedef const void* (__cdecl *ptr_simGetObject)(SIMHANDLE objID);

typedef const void* (__cdecl *ptr_simGetIkGroupObject)(int ikGroupID);
typedef int (__cdecl *ptr_simMpHandleIkGroupObject)(const void* ikGroup);

typedef bool (__cdecl *ptr_simIsShapeDynamicallyStatic)(const void* shape);
typedef int (__cdecl *ptr_simGetTreeDynamicProperty)(const void* object);
typedef int (__cdecl *ptr_simGetDummyLinkType)(const void* dummy,SIMHANDLE* linkedDummyID);
typedef int (__cdecl *ptr_simGetJointMode)(const void* joint);
typedef bool (__cdecl *ptr_simIsJointInHybridOperation)(const void* joint);
typedef void (__cdecl *ptr_simDisableDynamicTreeForManipulation)(const void* object,bool disableFlag);
typedef bool (__cdecl *ptr_simIsShapeDynamicallyRespondable)(const void* shape);
typedef int (__cdecl *ptr_simGetDynamicCollisionMask)(const void* shape);
typedef const void* (__cdecl *ptr_simGetLastParentForLocalGlobalCollidable)(const void* shape);
typedef bool (__cdecl *ptr_simGetStartSleeping)(const void* shape);
typedef bool (__cdecl *ptr_simGetWasPutToSleepOnce)(const void* shape);
typedef bool (__cdecl *ptr_simGetDynamicsFullRefreshFlag)(const void* object);
typedef void (__cdecl *ptr_simSetDynamicsFullRefreshFlag)(const void* object,bool flag);
typedef void (__cdecl *ptr_simClearAdditionalForceAndTorque)(const void* shape);
typedef int (__cdecl *ptr_simGetJointType)(const void* joint);
typedef const void* (__cdecl *ptr_simGetGeomWrapFromGeomProxy)(const void* geomData);
typedef int (__cdecl *ptr_simGetPurePrimitiveType)(const void* geomInfo);
typedef bool (__cdecl *ptr_simIsGeomWrapGeometric)(const void* geomInfo);
typedef bool (__cdecl *ptr_simIsGeomWrapConvex)(const void* geomInfo);
typedef int (__cdecl *ptr_simGetGeometricCount)(const void* geomInfo);
typedef void (__cdecl *ptr_simGetAllGeometrics)(const void* geomInfo,void** allGeometrics);
typedef void (__cdecl *ptr_simMakeDynamicAnnouncement)(int announceType);
typedef int (__cdecl *ptr_simGetTimeDiffInMs)(int previousTime);
typedef bool (__cdecl *ptr_simDoEntitiesCollide)(SIMHANDLE entity1ID,SIMHANDLE entity2ID,SIMHANDLE* cacheBuffer,bool overrideCollidableFlagIfShape1,bool overrideCollidableFlagIfShape2,bool pathPlanningRoutineCalling);
typedef int (__cdecl *ptr_simGetJointDynCtrlMode)(const void* joint);
typedef int (__cdecl *ptrSimFloatingViewRemove)(int floatingViewHandle);
#ifdef interfaceIsSinglePrecision
typedef int (__cdecl *ptrSimGetShapeViz)(SIMHANDLE shapeHandle,int index,struct SShapeVizInfof* info);
#else
typedef int (__cdecl *ptrSimGetShapeViz)(SIMHANDLE shapeHandle,int index,struct SShapeVizInfo* info);
#endif

typedef int (__cdecl *ptrSimTransformImage)(unsigned char* image,const int* resolution,int options,const SIMDOUBLE* floatParams,const int* intParams,void* reserved);
typedef const SIMDOUBLE* (__cdecl *ptrSimGetOctreeVoxels)(SIMHANDLE octreeHandle,int* ptCnt,void* reserved);
typedef const SIMDOUBLE* (__cdecl *ptrSimGetPointCloudPoints)(SIMHANDLE pointCloudHandle,int* ptCnt,void* reserved);
typedef int (__cdecl *ptrSimGetObjectMatrix)(SIMHANDLE objectHandle,SIMHANDLE relativeToObjectHandle,SIMDOUBLE* matrix);
typedef int (__cdecl *ptrSimSetObjectMatrix)(SIMHANDLE objectHandle,SIMHANDLE relativeToObjectHandle,const SIMDOUBLE* matrix);
typedef int (__cdecl *ptrSimGetObjectPose)(SIMHANDLE objectHandle,SIMHANDLE relativeToObjectHandle,SIMDOUBLE* pose);
typedef int (__cdecl *ptrSimSetObjectPose)(SIMHANDLE objectHandle,SIMHANDLE relativeToObjectHandle,const SIMDOUBLE* pose);
typedef int (__cdecl *ptrSimGetObjectPosition)(SIMHANDLE objectHandle,SIMHANDLE relativeToObjectHandle,SIMDOUBLE* position);
typedef int (__cdecl *ptrSimSetObjectPosition)(SIMHANDLE objectHandle,SIMHANDLE relativeToObjectHandle,const SIMDOUBLE* position);
typedef int (__cdecl *ptrSimGetObjectOrientation)(SIMHANDLE objectHandle,SIMHANDLE relativeToObjectHandle,SIMDOUBLE* eulerAngles);
typedef int (__cdecl *ptrSimSetObjectOrientation)(SIMHANDLE objectHandle,SIMHANDLE relativeToObjectHandle,const SIMDOUBLE* eulerAngles);
typedef int (__cdecl *ptrSimGetJointPosition)(SIMHANDLE objectHandle,SIMDOUBLE* position);
typedef int (__cdecl *ptrSimSetJointPosition)(SIMHANDLE objectHandle,SIMDOUBLE position);
typedef int (__cdecl *ptrSimSetJointTargetPosition)(SIMHANDLE objectHandle,SIMDOUBLE targetPosition);
typedef int (__cdecl *ptrSimGetJointTargetPosition)(SIMHANDLE objectHandle,SIMDOUBLE* targetPosition);
typedef int (__cdecl *ptrSimGetJointTargetForce)(SIMHANDLE jointHandle,SIMDOUBLE* forceOrTorque);
typedef int (__cdecl *ptrSimSetJointTargetForce)(SIMHANDLE objectHandle,SIMDOUBLE forceOrTorque,bool signedValue);
typedef int (__cdecl *ptrSimGetObjectChildPose)(SIMHANDLE objectHandle,SIMDOUBLE* pose);
typedef int (__cdecl *ptrSimSetObjectChildPose)(SIMHANDLE objectHandle,const SIMDOUBLE* pose);
typedef int (__cdecl *ptrSimGetJointInterval)(SIMHANDLE objectHandle,bool* cyclic,SIMDOUBLE* interval);
typedef int (__cdecl *ptrSimSetJointInterval)(SIMHANDLE objectHandle,bool cyclic,const SIMDOUBLE* interval);
typedef int (__cdecl *ptrSimBuildIdentityMatrix)(SIMDOUBLE* matrix);
typedef int (__cdecl *ptrSimBuildMatrix)(const SIMDOUBLE* position,const SIMDOUBLE* eulerAngles,SIMDOUBLE* matrix);
typedef int (__cdecl *ptrSimBuildPose)(const SIMDOUBLE* position,const SIMDOUBLE* eulerAngles,SIMDOUBLE* pose);
typedef int (__cdecl *ptrSimGetEulerAnglesFromMatrix)(const SIMDOUBLE* matrix,SIMDOUBLE* eulerAngles);
typedef int (__cdecl *ptrSimInvertMatrix)(SIMDOUBLE* matrix);
typedef int (__cdecl *ptrSimMultiplyMatrices)(const SIMDOUBLE* matrixIn1,const SIMDOUBLE* matrixIn2,SIMDOUBLE* matrixOut);
typedef int (__cdecl *ptrSimMultiplyPoses)(const SIMDOUBLE* poseIn1,const SIMDOUBLE* poseIn2,SIMDOUBLE* poseOut);
typedef int (__cdecl *ptrSimInvertPose)(SIMDOUBLE* pose);
typedef int (__cdecl *ptrSimInterpolatePoses)(const SIMDOUBLE* poseIn1,const SIMDOUBLE* poseIn2,SIMDOUBLE interpolFactor,SIMDOUBLE* poseOut);
typedef int (__cdecl *ptrSimPoseToMatrix)(const SIMDOUBLE* poseIn,SIMDOUBLE* matrixOut);
typedef int (__cdecl *ptrSimMatrixToPose)(const SIMDOUBLE* matrixIn,SIMDOUBLE* poseOut);
typedef int (__cdecl *ptrSimInterpolateMatrices)(const SIMDOUBLE* matrixIn1,const SIMDOUBLE* matrixIn2,SIMDOUBLE interpolFactor,SIMDOUBLE* matrixOut);
typedef int (__cdecl *ptrSimTransformVector)(const SIMDOUBLE* matrix,SIMDOUBLE* vect);
typedef SIMDOUBLE (__cdecl *ptrSimGetSimulationTime)();
typedef SIMDOUBLE (__cdecl *ptrSimGetSystemTime)();
typedef int (__cdecl *ptrSimHandleProximitySensor)(SIMHANDLE sensorHandle,SIMDOUBLE* detectedPoint,SIMHANDLE* detectedObjectHandle,SIMDOUBLE* normalVector);
typedef int (__cdecl *ptrSimReadProximitySensor)(SIMHANDLE sensorHandle,SIMDOUBLE* detectedPoint,SIMHANDLE* detectedObjectHandle,SIMDOUBLE* normalVector);
typedef int (__cdecl *ptrSimHandleDynamics)(SIMDOUBLE deltaTime);
typedef int (__cdecl *ptrSimCheckProximitySensor)(SIMHANDLE sensorHandle,SIMHANDLE entityHandle,SIMDOUBLE* detectedPoint);
typedef int (__cdecl *ptrSimCheckProximitySensorEx)(SIMHANDLE sensorHandle,SIMHANDLE entityHandle,int detectionMode,SIMDOUBLE detectionThreshold,SIMDOUBLE maxAngle,SIMDOUBLE* detectedPoint,SIMHANDLE* detectedObjectHandle,SIMDOUBLE* normalVector);
typedef int (__cdecl *ptrSimCheckProximitySensorEx2)(SIMHANDLE sensorHandle,SIMDOUBLE* vertexPointer,int itemType,int itemCount,int detectionMode,SIMDOUBLE detectionThreshold,SIMDOUBLE maxAngle,SIMDOUBLE* detectedPoint,SIMDOUBLE* normalVector);
typedef int (__cdecl *ptrSimCheckCollisionEx)(SIMHANDLE entity1Handle,SIMHANDLE entity2Handle,SIMDOUBLE** intersectionSegments);
typedef int (__cdecl *ptrSimCheckDistance)(SIMHANDLE entity1Handle,SIMHANDLE entity2Handle,SIMDOUBLE threshold,SIMDOUBLE* distanceData);
typedef int (__cdecl *ptrSimSetSimulationTimeStep)(SIMDOUBLE timeStep);
typedef SIMDOUBLE (__cdecl *ptrSimGetSimulationTimeStep)();
typedef int (__cdecl *ptrSimFloatingViewAdd)(SIMDOUBLE posX,SIMDOUBLE posY,SIMDOUBLE sizeX,SIMDOUBLE sizeY,int options);
typedef int (__cdecl *ptrSimHandleGraph)(SIMHANDLE graphHandle,SIMDOUBLE simulationTime);
typedef int (__cdecl *ptrSimSetGraphStreamTransformation)(SIMHANDLE graphHandle,int streamId,int trType,SIMDOUBLE mult,SIMDOUBLE off,int movingAvgPeriod);
typedef int (__cdecl *ptrSimAddGraphCurve)(SIMHANDLE graphHandle,const char* curveName,int dim,const int* streamIds,const SIMDOUBLE* defaultValues,const char* unitStr,int options,const float* color,int curveWidth);
typedef int (__cdecl *ptrSimSetGraphStreamValue)(SIMHANDLE graphHandle,int streamId,SIMDOUBLE value);
typedef int (__cdecl *ptrSimSetJointTargetVelocity)(SIMHANDLE objectHandle,SIMDOUBLE targetVelocity);
typedef int (__cdecl *ptrSimGetJointTargetVelocity)(SIMHANDLE objectHandle,SIMDOUBLE* targetVelocity);
typedef int (__cdecl *ptrSimScaleObjects)(const SIMHANDLE* objectHandles,int objectCount,SIMDOUBLE scalingFactor,bool scalePositionsToo);
typedef SIMHANDLE (__cdecl *ptrSimAddDrawingObject)(int objectType,SIMDOUBLE size,SIMDOUBLE duplicateTolerance,SIMHANDLE parentObjectHandle,int maxItemCount,const float* color,const float* setToNULL,const float* setToNULL2,const float* setToNULL3);
typedef int (__cdecl *ptrSimAddGraphStream)(SIMHANDLE graphHandle,const char* streamName,const char* unitStr,int options,const float* color,SIMDOUBLE cyclicRange);
typedef int (__cdecl *ptrSimAddDrawingObjectItem)(SIMHANDLE objectHandle,const SIMDOUBLE* itemData);
typedef SIMDOUBLE (__cdecl *ptrSimGetObjectSizeFactor)(SIMHANDLE objectHandle);
typedef int (__cdecl *ptrSimReadForceSensor)(SIMHANDLE objectHandle,SIMDOUBLE* forceVector,SIMDOUBLE* torqueVector);
typedef int (__cdecl *ptrSimGetVelocity)(SIMHANDLE shapeHandle,SIMDOUBLE* linearVelocity,SIMDOUBLE* angularVelocity);
typedef int (__cdecl *ptrSimGetObjectVelocity)(SIMHANDLE objectHandle,SIMDOUBLE* linearVelocity,SIMDOUBLE* angularVelocity);
typedef int (__cdecl *ptrSimGetJointVelocity)(SIMHANDLE jointHandle,SIMDOUBLE* velocity);
typedef int (__cdecl *ptrSimAddForceAndTorque)(SIMHANDLE shapeHandle,const SIMDOUBLE* force,const SIMDOUBLE* torque);
typedef int (__cdecl *ptrSimAddForce)(SIMHANDLE shapeHandle,const SIMDOUBLE* position,const SIMDOUBLE* force);
typedef int (__cdecl *ptrSimSetObjectColor)(SIMHANDLE objectHandle,int index,int colorComponent,const float* rgbData);
typedef int (__cdecl *ptrSimGetObjectColor)(SIMHANDLE objectHandle,int index,int colorComponent,float* rgbData);
typedef int (__cdecl *ptrSimSetShapeColor)(SIMHANDLE shapeHandle,const char* colorName,int colorComponent,const float* rgbData);
typedef int (__cdecl *ptrSimGetShapeColor)(SIMHANDLE shapeHandle,const char* colorName,int colorComponent,float* rgbData);
typedef int (__cdecl *ptrSimGetContactInfo)(int dynamicPass,SIMHANDLE objectHandle,int index,SIMHANDLE* objectHandles,SIMDOUBLE* contactInfo);
typedef int (__cdecl *ptrSimAuxiliaryConsoleOpen)(const char* title,int maxLines,int mode,const int* position,const int* size,const float* textColor,const float* backgroundColor);
typedef SIMHANDLE (__cdecl *ptrSimImportShape)(int fileformat,const char* pathAndFilename,int options,SIMDOUBLE identicalVerticeTolerance,SIMDOUBLE scalingFactor);
typedef int (__cdecl *ptrSimImportMesh)(int fileformat,const char* pathAndFilename,int options,SIMDOUBLE identicalVerticeTolerance,SIMDOUBLE scalingFactor,SIMDOUBLE*** vertices,int** verticesSizes,int*** indices,int** indicesSizes,SIMDOUBLE*** reserved,char*** names);
typedef int (__cdecl *ptrSimExportMesh)(int fileformat,const char* pathAndFilename,int options,SIMDOUBLE scalingFactor,int elementCount,const SIMDOUBLE** vertices,const int* verticesSizes,const int** indices,const int* indicesSizes,SIMDOUBLE** reserved,const char** names);
typedef SIMHANDLE (__cdecl *ptrSimCreateShape)(int options,double shadingAngle,const double* vertices,int verticesSize,const int* indices,int indicesSize,const double* normals,const float* textCoords,const unsigned char* texture,const int* textureResolution);
typedef SIMHANDLE (__cdecl *ptrSimCreateMeshShape)(int options,SIMDOUBLE shadingAngle,const SIMDOUBLE* vertices,int verticesSize,const int* indices,int indicesSize,SIMDOUBLE* reserved);
typedef SIMHANDLE (__cdecl *ptrSimCreatePrimitiveShape)(int primitiveType,const SIMDOUBLE* sizes,int options);
typedef SIMHANDLE (__cdecl *ptrSimCreateHeightfieldShape)(int options,SIMDOUBLE shadingAngle,int xPointCount,int yPointCount,SIMDOUBLE xSize,const SIMDOUBLE* heights);
typedef int (__cdecl *ptrSimGetShapeMesh)(SIMHANDLE shapeHandle,SIMDOUBLE** vertices,int* verticesSize,int** indices,int* indicesSize,SIMDOUBLE** normals);
typedef SIMHANDLE (__cdecl *ptrSimCreateJoint)(int jointType,int jointMode,int options,const SIMDOUBLE* sizes,const SIMDOUBLE* reservedA,const SIMDOUBLE* reservedB);
typedef SIMHANDLE (__cdecl *ptrSimCreateDummy)(SIMDOUBLE size,const float* reserved);
typedef SIMHANDLE (__cdecl *ptrSimCreateScript)(int scriptType,const char* scriptText, int options, const char* lang);
typedef int (__cdecl *ptrSimGetObjectHierarchyOrder)(SIMHANDLE objectHandle, int* totalSiblings);
typedef int (__cdecl *ptrSimSetObjectHierarchyOrder)(SIMHANDLE objectHandle, int order);
typedef SIMHANDLE (__cdecl *ptrSimCreateForceSensor)(int options,const int* intParams,const SIMDOUBLE* floatParams,const SIMDOUBLE* reserved);
typedef SIMHANDLE (__cdecl *ptrSimCreateVisionSensor)(int options,const int* intParams,const SIMDOUBLE* floatParams,const SIMDOUBLE* reserved);
typedef SIMHANDLE (__cdecl *ptrSimCreateProximitySensor)(int sensorType,int subType,int options,const int* intParams,const SIMDOUBLE* floatParams,const SIMDOUBLE* reserved);
typedef int (__cdecl *ptrSimGetRotationAxis)(const SIMDOUBLE* matrixStart,const SIMDOUBLE* matrixGoal,SIMDOUBLE* axis,SIMDOUBLE* angle);
typedef int (__cdecl *ptrSimRotateAroundAxis)(const SIMDOUBLE* matrixIn,const SIMDOUBLE* axis,const SIMDOUBLE* axisPos,SIMDOUBLE angle,SIMDOUBLE* matrixOut);
typedef int (__cdecl *ptrSimGetJointForce)(SIMHANDLE jointHandle,SIMDOUBLE* forceOrTorque);
typedef int (__cdecl *ptrSimCameraFitToView)(SIMHANDLE viewHandleOrIndex,int objectCount,const SIMHANDLE* objectHandles,int options,SIMDOUBLE scaling);
typedef int (__cdecl *ptrSimHandleVisionSensor)(SIMHANDLE visionSensorHandle,SIMDOUBLE** auxValues,int** auxValuesCount);
typedef int (__cdecl *ptrSimReadVisionSensor)(SIMHANDLE visionSensorHandle,SIMDOUBLE** auxValues,int** auxValuesCount);
typedef int (__cdecl *ptrSimCheckVisionSensor)(SIMHANDLE visionSensorHandle,SIMHANDLE entityHandle,SIMDOUBLE** auxValues,int** auxValuesCount);
typedef unsigned char* (__cdecl *ptrSimGetVisionSensorImg)(SIMHANDLE sensorHandle,int options,SIMDOUBLE rgbaCutOff,const int* pos,const int* size,int* resolution);
typedef int (__cdecl *ptrSimGetVisionSensorRes)(SIMHANDLE visionSensorHandle,int* resolution);
typedef int (__cdecl *ptrSimGetObjectQuaternion)(SIMHANDLE objectHandle,SIMHANDLE relativeToObjectHandle,SIMDOUBLE* quaternion);
typedef int (__cdecl *ptrSimSetObjectQuaternion)(SIMHANDLE objectHandle,SIMHANDLE relativeToObjectHandle,const SIMDOUBLE* quaternion);
typedef SIMHANDLE (__cdecl *ptrSimConvexDecompose)(SIMHANDLE shapeHandle,int options,const int* intParams,const SIMDOUBLE* floatParams);
typedef int (__cdecl *ptrSimWriteTexture)(SIMHANDLE textureId,int options,const char* data,int posX,int posY,int sizeX,int sizeY,SIMDOUBLE interpol);
typedef SIMHANDLE (__cdecl *ptrSimCreateTexture)(const char* fileName,int options,const SIMDOUBLE* planeSizes,const SIMDOUBLE* scalingUV,const SIMDOUBLE* xy_g,int fixedResolution,int* textureId,int* resolution,const void* reserved);
typedef int (__cdecl *ptrSimGetShapeGeomInfo)(SIMHANDLE shapeHandle,int* intData,SIMDOUBLE* floatData,void* reserved);
typedef int (__cdecl *ptrSimScaleObject)(SIMHANDLE objectHandle,SIMDOUBLE xScale,SIMDOUBLE yScale,SIMDOUBLE zScale,int options);
typedef int (__cdecl *ptrSimSetShapeTexture)(SIMHANDLE shapeHandle,SIMHANDLE textureId,int mappingMode,int options,const SIMDOUBLE* uvScaling,const SIMDOUBLE* position,const SIMDOUBLE* orientation);
typedef int (__cdecl *ptrSimGetQHull)(const SIMDOUBLE* inVertices,int inVerticesL,SIMDOUBLE** verticesOut,int* verticesOutL,int** indicesOut,int* indicesOutL,int reserved1,const SIMDOUBLE* reserved2);
typedef int (__cdecl *ptrSimGetDecimatedMesh)(const SIMDOUBLE* inVertices,int inVerticesL,const int* inIndices,int inIndicesL,SIMDOUBLE** verticesOut,int* verticesOutL,int** indicesOut,int* indicesOutL,SIMDOUBLE decimationPercent,int reserved1,const SIMDOUBLE* reserved2);
typedef int (__cdecl *ptrSimComputeMassAndInertia)(SIMHANDLE shapeHandle,SIMDOUBLE density);
typedef SIMHANDLE (__cdecl *ptrSimCreateOctree)(SIMDOUBLE voxelSize,int options,SIMDOUBLE pointSize,void* reserved);
typedef SIMHANDLE (__cdecl *ptrSimCreatePointCloud)(SIMDOUBLE maxVoxelSize,int maxPtCntPerVoxel,int options,SIMDOUBLE pointSize,void* reserved);
typedef int (__cdecl *ptrSimSetPointCloudOptions)(SIMHANDLE pointCloudHandle,SIMDOUBLE maxVoxelSize,int maxPtCntPerVoxel,int options,SIMDOUBLE pointSize,void* reserved);
typedef int (__cdecl *ptrSimGetPointCloudOptions)(SIMHANDLE pointCloudHandle,SIMDOUBLE* maxVoxelSize,int* maxPtCntPerVoxel,int* options,SIMDOUBLE* pointSize,void* reserved);
typedef int (__cdecl *ptrSimInsertVoxelsIntoOctree)(SIMHANDLE octreeHandle,int options,const SIMDOUBLE* pts,int ptCnt,const unsigned char* color,const unsigned int* tag,void* reserved);
typedef int (__cdecl *ptrSimRemoveVoxelsFromOctree)(SIMHANDLE octreeHandle,int options,const SIMDOUBLE* pts,int ptCnt,void* reserved);
typedef int (__cdecl *ptrSimInsertPointsIntoPointCloud)(SIMHANDLE pointCloudHandle,int options,const SIMDOUBLE* pts,int ptCnt,const unsigned char* color,void* optionalValues);
typedef int (__cdecl *ptrSimRemovePointsFromPointCloud)(SIMHANDLE pointCloudHandle,int options,const SIMDOUBLE* pts,int ptCnt,SIMDOUBLE tolerance,void* reserved);
typedef int (__cdecl *ptrSimIntersectPointsWithPointCloud)(SIMHANDLE pointCloudHandle,int options,const SIMDOUBLE* pts,int ptCnt,SIMDOUBLE tolerance,void* reserved);
typedef int (__cdecl *ptrSimInsertObjectIntoPointCloud)(SIMHANDLE pointCloudHandle,SIMHANDLE objectHandle,int options,SIMDOUBLE gridSize,const unsigned char* color,void* optionalValues);
typedef int (__cdecl *ptrSimSubtractObjectFromPointCloud)(SIMHANDLE pointCloudHandle,SIMHANDLE objectHandle,int options,SIMDOUBLE tolerance,void* reserved);
typedef int (__cdecl *ptrSimCheckOctreePointOccupancy)(SIMHANDLE octreeHandle,int options,const SIMDOUBLE* points,int ptCnt,unsigned int* tag,unsigned long long int* location,void* reserved);
typedef int (__cdecl *ptrSimApplyTexture)(SIMHANDLE shapeHandle,const SIMDOUBLE* textureCoordinates,int textCoordSize,const unsigned char* texture,const int* textureResolution,int options);
typedef int (__cdecl *ptrSimSetJointDependency)(SIMHANDLE jointHandle,SIMHANDLE masterJointHandle,SIMDOUBLE offset,SIMDOUBLE multCoeff);
typedef int (__cdecl *ptrSimGetJointDependency)(SIMHANDLE jointHandle,SIMHANDLE* masterJointHandle,SIMDOUBLE* offset,SIMDOUBLE* multCoeff);
typedef int (__cdecl *ptrSimGetShapeMass)(SIMHANDLE shapeHandle,SIMDOUBLE* mass);
typedef int (__cdecl *ptrSimSetShapeMass)(SIMHANDLE shapeHandle,SIMDOUBLE mass);
typedef int (__cdecl *ptrSimGetShapeInertia)(SIMHANDLE shapeHandle,SIMDOUBLE* inertiaMatrix,SIMDOUBLE* transformationMatrix);
typedef int (__cdecl *ptrSimSetShapeInertia)(SIMHANDLE shapeHandle,const SIMDOUBLE* inertiaMatrix,const SIMDOUBLE* transformationMatrix);
typedef SIMHANDLE (__cdecl *ptrSimGenerateShapeFromPath)(const SIMDOUBLE* path,int pathSize,const SIMDOUBLE* section,int sectionSize,int options,const SIMDOUBLE* upVector,SIMDOUBLE reserved);
typedef SIMDOUBLE (__cdecl *ptrSimGetClosestPosOnPath)(const SIMDOUBLE* path,int pathSize,const SIMDOUBLE* pathLengths,const SIMDOUBLE* absPt);
typedef void (__cdecl *ptr_simGetObjectLocalTransformation)(const void* object,SIMDOUBLE* pos,SIMDOUBLE* quat,bool excludeFirstJointTransformation);
typedef void (__cdecl *ptr_simSetObjectLocalTransformation)(void* object,const SIMDOUBLE* pos,const SIMDOUBLE* quat,SIMDOUBLE simTime);
typedef void (__cdecl *ptr_simDynReportObjectCumulativeTransformation)(void* object,const SIMDOUBLE* pos,const SIMDOUBLE* quat,SIMDOUBLE simTime);
typedef void (__cdecl *ptr_simSetObjectCumulativeTransformation)(void* object,const SIMDOUBLE* pos,const SIMDOUBLE* quat,bool keepChildrenInPlace);
typedef void (__cdecl *ptr_simGetObjectCumulativeTransformation)(const void* object,SIMDOUBLE* pos,SIMDOUBLE* quat,bool excludeFirstJointTransformation);
typedef void (__cdecl *ptr_simSetJointVelocity)(const void* joint,SIMDOUBLE vel);
typedef void (__cdecl *ptr_simSetJointPosition)(const void* joint,SIMDOUBLE pos);
typedef SIMDOUBLE (__cdecl *ptr_simGetJointPosition)(const void* joint);
typedef void (__cdecl *ptr_simSetDynamicMotorPositionControlTargetPosition)(const void* joint,SIMDOUBLE pos);
typedef void (__cdecl *ptr_simGetInitialDynamicVelocity)(const void* shape,SIMDOUBLE* vel);
typedef void (__cdecl *ptr_simSetInitialDynamicVelocity)(void* shape,const SIMDOUBLE* vel);
typedef void (__cdecl *ptr_simGetInitialDynamicAngVelocity)(const void* shape,SIMDOUBLE* angularVel);
typedef void (__cdecl *ptr_simSetInitialDynamicAngVelocity)(void* shape,const SIMDOUBLE* angularVel);
typedef void (__cdecl *ptr_simSetShapeDynamicVelocity)(void* shape,const SIMDOUBLE* linear,const SIMDOUBLE* angular,SIMDOUBLE simTime);
typedef void (__cdecl *ptr_simGetAdditionalForceAndTorque)(const void* shape,SIMDOUBLE* force,SIMDOUBLE* torque);
typedef bool (__cdecl *ptr_simGetJointPositionInterval)(const void* joint,SIMDOUBLE* minValue,SIMDOUBLE* rangeValue);
typedef SIMDOUBLE (__cdecl *ptr_simGetDynamicMotorTargetPosition)(const void* joint);
typedef SIMDOUBLE (__cdecl *ptr_simGetDynamicMotorTargetVelocity)(const void* joint);
typedef SIMDOUBLE (__cdecl *ptr_simGetDynamicMotorMaxForce)(const void* joint);
typedef SIMDOUBLE (__cdecl *ptr_simGetDynamicMotorUpperLimitVelocity)(const void* joint);
typedef void (__cdecl *ptr_simSetDynamicMotorReflectedPositionFromDynamicEngine)(void* joint,SIMDOUBLE pos,SIMDOUBLE simTime);
typedef void (__cdecl *ptr_simSetJointSphericalTransformation)(void* joint,const SIMDOUBLE* quat,SIMDOUBLE simTime);
typedef void (__cdecl *ptr_simAddForceSensorCumulativeForcesAndTorques)(void* forceSensor,const SIMDOUBLE* force,const SIMDOUBLE* torque,int totalPassesCount,SIMDOUBLE simTime);
typedef void (__cdecl *ptr_simAddJointCumulativeForcesOrTorques)(void* joint,SIMDOUBLE forceOrTorque,int totalPassesCount,SIMDOUBLE simTime);
typedef SIMDOUBLE (__cdecl *ptr_simGetMass)(const void* geomInfo);
typedef SIMDOUBLE (__cdecl *ptr_simGetLocalInertiaInfo)(const void* object,SIMDOUBLE* pos,SIMDOUBLE* quat,SIMDOUBLE* diagI);
typedef void (__cdecl *ptr_simGetPurePrimitiveSizes)(const void* geometric,SIMDOUBLE* sizes);
typedef void (__cdecl *ptr_simGetVerticesLocalFrame)(const void* shape,const void* geometric,SIMDOUBLE* pos,SIMDOUBLE* quat);
typedef const SIMDOUBLE* (__cdecl *ptr_simGetHeightfieldData)(const void* geometric,int* xCount,int* yCount,SIMDOUBLE* minHeight,SIMDOUBLE* maxHeight);
typedef void (__cdecl *ptr_simGetCumulativeMeshes)(const void* shape,const void* geomInfo,SIMDOUBLE** vertices,int* verticesSize,int** indices,int* indicesSize);
typedef void (__cdecl *ptr_simGetGravity)(SIMDOUBLE* gravity);
typedef bool (__cdecl *ptr_simGetDistanceBetweenEntitiesIfSmaller)(SIMHANDLE entity1ID,SIMHANDLE entity2ID,SIMDOUBLE* distance,SIMDOUBLE* ray,int* cacheBuffer,bool overrideMeasurableFlagIfNonCollection1,bool overrideMeasurableFlagIfNonCollection2,bool pathPlanningRoutineCalling);
typedef int (__cdecl *ptr_simHandleJointControl)(const void* joint,int auxV,const int* inputValuesInt,const SIMDOUBLE* inputValuesFloat,SIMDOUBLE* outputValues);
typedef int (__cdecl *ptr_simHandleCustomContact)(SIMHANDLE objHandle1,SIMHANDLE objHandle2,int engine,int* dataInt,SIMDOUBLE* dataFloat);
typedef SIMDOUBLE (__cdecl *ptr_simGetPureHollowScaling)(const void* geometric);
typedef void (__cdecl *ptr_simDynCallback)(const int* intData,const SIMDOUBLE* floatData);


extern ptrSimSetBoolProperty simSetBoolProperty;
extern ptrSimGetBoolProperty simGetBoolProperty;
extern ptrSimSetIntProperty simSetIntProperty;
extern ptrSimGetIntProperty simGetIntProperty;
extern ptrSimSetLongProperty simSetLongProperty;
extern ptrSimGetLongProperty simGetLongProperty;
extern ptrSimSetFloatProperty simSetFloatProperty;
extern ptrSimGetFloatProperty simGetFloatProperty;
extern ptrSimSetStringProperty simSetStringProperty;
extern ptrSimGetStringProperty simGetStringProperty;
extern ptrSimSetTableProperty simSetTableProperty;
extern ptrSimGetTableProperty simGetTableProperty;
extern ptrSimSetBufferProperty simSetBufferProperty;
extern ptrSimGetBufferProperty simGetBufferProperty;
extern ptrSimSetIntArray2Property simSetIntArray2Property;
extern ptrSimGetIntArray2Property simGetIntArray2Property;
extern ptrSimSetVector2Property simSetVector2Property;
extern ptrSimGetVector2Property simGetVector2Property;
extern ptrSimSetVector3Property simSetVector3Property;
extern ptrSimGetVector3Property simGetVector3Property;
extern ptrSimSetQuaternionProperty simSetQuaternionProperty;
extern ptrSimGetQuaternionProperty simGetQuaternionProperty;
extern ptrSimSetPoseProperty simSetPoseProperty;
extern ptrSimGetPoseProperty simGetPoseProperty;
extern ptrSimSetColorProperty simSetColorProperty;
extern ptrSimGetColorProperty simGetColorProperty;
extern ptrSimSetFloatArrayProperty simSetFloatArrayProperty;
extern ptrSimGetFloatArrayProperty simGetFloatArrayProperty;
extern ptrSimSetIntArrayProperty simSetIntArrayProperty;
extern ptrSimGetIntArrayProperty simGetIntArrayProperty;
extern ptrSimRemoveProperty simRemoveProperty;
extern ptrSimGetPropertyName simGetPropertyName;
extern ptrSimGetPropertyInfo simGetPropertyInfo;

extern ptrSimRegCallback simRegCallback;
extern ptrSimRunGui simRunGui;
extern ptrSimInitialize simInitialize;
extern ptrSimDeinitialize simDeinitialize;
extern ptrSimPostExitRequest simPostExitRequest;
extern ptrSimGetExitRequest simGetExitRequest;
extern ptrSimLoop simLoop;
extern ptrSimTest simTest;
extern ptrSimGetSimulatorMessage simGetSimulatorMessage;
extern ptrSimGetMainWindow simGetMainWindow;
extern ptrSimGetLastError simGetLastError;
extern ptrSimGetLastInfo simGetLastInfo;
extern ptrSimGetObject simGetObject;
extern ptrSimGetObjectUid simGetObjectUid;
extern ptrSimGetObjectFromUid simGetObjectFromUid;
extern ptrSimGetScriptHandleEx simGetScriptHandleEx;
extern ptrSimRemoveObjects simRemoveObjects;
extern ptrSimRemoveModel simRemoveModel;
extern ptrSimGetObjectAlias simGetObjectAlias;
extern ptrSimSetObjectAlias simSetObjectAlias;
extern ptrSimGetObjectMatrix simGetObjectMatrix;
extern ptrSimSetObjectMatrix simSetObjectMatrix;
extern ptrSimGetObjectPose simGetObjectPose;
extern ptrSimSetObjectPose simSetObjectPose;
extern ptrSimGetObjectPosition simGetObjectPosition;
extern ptrSimSetObjectPosition simSetObjectPosition;
extern ptrSimGetObjectOrientation simGetObjectOrientation;
extern ptrSimSetObjectOrientation simSetObjectOrientation;
extern ptrSimGetJointPosition simGetJointPosition;
extern ptrSimSetJointPosition simSetJointPosition;
extern ptrSimSetJointTargetPosition simSetJointTargetPosition;
extern ptrSimGetJointTargetPosition simGetJointTargetPosition;
extern ptrSimGetObjectChildPose simGetObjectChildPose;
extern ptrSimSetObjectChildPose simSetObjectChildPose;
extern ptrSimGetJointInterval simGetJointInterval;
extern ptrSimSetJointInterval simSetJointInterval;
extern ptrSimGetObjectParent simGetObjectParent;
extern ptrSimGetObjectChild simGetObjectChild;
extern ptrSimSetObjectParent simSetObjectParent;
extern ptrSimGetObjectType simGetObjectType;
extern ptrSimGetJointType simGetJointType;
extern ptrSimBuildIdentityMatrix simBuildIdentityMatrix;
extern ptrSimBuildMatrix simBuildMatrix;
extern ptrSimBuildPose simBuildPose;
extern ptrSimGetEulerAnglesFromMatrix simGetEulerAnglesFromMatrix;
extern ptrSimInvertMatrix simInvertMatrix;
extern ptrSimMultiplyMatrices simMultiplyMatrices;
extern ptrSimMultiplyPoses simMultiplyPoses;
extern ptrSimInvertPose simInvertPose;
extern ptrSimInterpolatePoses simInterpolatePoses;
extern ptrSimPoseToMatrix simPoseToMatrix;
extern ptrSimMatrixToPose simMatrixToPose;
extern ptrSimInterpolateMatrices simInterpolateMatrices;
extern ptrSimTransformVector simTransformVector;
extern ptrSimReservedCommand simReservedCommand;
extern ptrSimGetSimulationTime simGetSimulationTime;
extern ptrSimGetSimulationState simGetSimulationState;
extern ptrSimGetSystemTime simGetSystemTime;
extern ptrSimLoadScene simLoadScene;
extern ptrSimCloseScene simCloseScene;
extern ptrSimSaveScene simSaveScene;
extern ptrSimLoadModel simLoadModel;
extern ptrSimSaveModel simSaveModel;
extern ptrSimDoesFileExist simDoesFileExist;
extern ptrSimGetObjectSel simGetObjectSel;
extern ptrSimSetObjectSel simSetObjectSel;
extern ptrSimHandleProximitySensor simHandleProximitySensor;
extern ptrSimReadProximitySensor simReadProximitySensor;
extern ptrSimHandleDynamics simHandleDynamics;
extern ptrSimResetScript simResetScript;
extern ptrSimRefreshDialogs simRefreshDialogs;
extern ptrSimResetProximitySensor simResetProximitySensor;
extern ptrSimCheckProximitySensor simCheckProximitySensor;
extern ptrSimCheckProximitySensorEx simCheckProximitySensorEx;
extern ptrSimCheckProximitySensorEx2 simCheckProximitySensorEx2;
extern ptrSimCreateBuffer simCreateBuffer;
extern ptrSimReleaseBuffer simReleaseBuffer;
extern ptrSimCheckCollision simCheckCollision;
extern ptrSimCheckCollisionEx simCheckCollisionEx;
extern ptrSimCheckDistance simCheckDistance;
extern ptrSimSetSimulationTimeStep simSetSimulationTimeStep;
extern ptrSimGetSimulationTimeStep simGetSimulationTimeStep;
extern ptrSimGetRealTimeSimulation simGetRealTimeSimulation;
extern ptrSimStartSimulation simStartSimulation;
extern ptrSimStopSimulation simStopSimulation;
extern ptrSimPauseSimulation simPauseSimulation;
extern ptrSimFloatingViewAdd simFloatingViewAdd;
extern ptrSimFloatingViewRemove simFloatingViewRemove;
extern ptrSimAdjustView simAdjustView;
extern ptrSimSetLastError simSetLastError;
extern ptrSimHandleGraph simHandleGraph;
extern ptrSimResetGraph simResetGraph;
extern ptrSimAddGraphStream simAddGraphStream;
extern ptrSimDestroyGraphCurve simDestroyGraphCurve;
extern ptrSimSetGraphStreamTransformation simSetGraphStreamTransformation;
extern ptrSimDuplicateGraphCurveToStatic simDuplicateGraphCurveToStatic;
extern ptrSimAddGraphCurve simAddGraphCurve;
extern ptrSimSetGraphStreamValue simSetGraphStreamValue;
extern ptrSimSetNavigationMode simSetNavigationMode;
extern ptrSimGetNavigationMode simGetNavigationMode;
extern ptrSimSetPage simSetPage;
extern ptrSimGetPage simGetPage;
extern ptrSimRegisterScriptCallbackFunction simRegisterScriptCallbackFunction;
extern ptrSimRegisterScriptVariable simRegisterScriptVariable;
extern ptrSimRegisterScriptFuncHook simRegisterScriptFuncHook;
extern ptrSimSetJointTargetVelocity simSetJointTargetVelocity;
extern ptrSimGetJointTargetVelocity simGetJointTargetVelocity;
extern ptrSimCopyPasteObjects simCopyPasteObjects;
extern ptrSimScaleObjects simScaleObjects;
extern ptrSimAddDrawingObject simAddDrawingObject;
extern ptrSimRemoveDrawingObject simRemoveDrawingObject;
extern ptrSimAddDrawingObjectItem simAddDrawingObjectItem;
extern ptrSimGetObjectSizeFactor simGetObjectSizeFactor;
extern ptrSimAnnounceSceneContentChange simAnnounceSceneContentChange;
extern ptrSimReadForceSensor simReadForceSensor;
extern ptrSimGetVelocity simGetVelocity;
extern ptrSimGetObjectVelocity simGetObjectVelocity;
extern ptrSimGetJointVelocity simGetJointVelocity;
extern ptrSimAddForceAndTorque simAddForceAndTorque;
extern ptrSimAddForce simAddForce;
extern ptrSimSetExplicitHandling simSetExplicitHandling;
extern ptrSimGetExplicitHandling simGetExplicitHandling;
extern ptrSimGetLinkDummy simGetLinkDummy;
extern ptrSimSetLinkDummy simSetLinkDummy;
extern ptrSimSetObjectColor simSetObjectColor;
extern ptrSimGetObjectColor simGetObjectColor;
extern ptrSimSetShapeColor simSetShapeColor;
extern ptrSimGetShapeColor simGetShapeColor;
extern ptrSimResetDynamicObject simResetDynamicObject;
extern ptrSimSetJointMode simSetJointMode;
extern ptrSimGetJointMode simGetJointMode;
extern ptrSimSerialOpen simSerialOpen;
extern ptrSimSerialClose simSerialClose;
extern ptrSimSerialSend simSerialSend;
extern ptrSimSerialRead simSerialRead;
extern ptrSimSerialCheck simSerialCheck;
extern ptrSimGetContactInfo simGetContactInfo;
extern ptrSimAuxiliaryConsoleOpen simAuxiliaryConsoleOpen;
extern ptrSimAuxiliaryConsoleClose simAuxiliaryConsoleClose;
extern ptrSimAuxiliaryConsoleShow simAuxiliaryConsoleShow;
extern ptrSimAuxiliaryConsolePrint simAuxiliaryConsolePrint;
extern ptrSimImportShape simImportShape;
extern ptrSimImportMesh simImportMesh;
extern ptrSimExportMesh simExportMesh;
extern ptrSimCreateShape simCreateShape;
extern ptrSimCreateMeshShape simCreateMeshShape;
extern ptrSimCreatePrimitiveShape simCreatePrimitiveShape;
extern ptrSimCreateHeightfieldShape simCreateHeightfieldShape;
extern ptrSimGetShapeMesh simGetShapeMesh;
extern ptrSimCreateJoint simCreateJoint;
extern ptrSimCreateDummy simCreateDummy;
extern ptrSimCreateScript simCreateScript;
extern ptrSimGetObjectHierarchyOrder simGetObjectHierarchyOrder;
extern ptrSimSetObjectHierarchyOrder simSetObjectHierarchyOrder;
extern ptrSimCreateForceSensor simCreateForceSensor;
extern ptrSimCreateVisionSensor simCreateVisionSensor;
extern ptrSimCreateProximitySensor simCreateProximitySensor;
extern ptrSimGetRotationAxis simGetRotationAxis;
extern ptrSimRotateAroundAxis simRotateAroundAxis;
extern ptrSimGetJointForce simGetJointForce;
extern ptrSimGetJointTargetForce simGetJointTargetForce;
extern ptrSimSetJointTargetForce simSetJointTargetForce;
extern ptrSimCameraFitToView simCameraFitToView;
extern ptrSimIsHandle simIsHandle;
extern ptrSimHandleVisionSensor simHandleVisionSensor;
extern ptrSimReadVisionSensor simReadVisionSensor;
extern ptrSimResetVisionSensor simResetVisionSensor;
extern ptrSimCheckVisionSensor simCheckVisionSensor;
extern ptrSimCheckVisionSensorEx simCheckVisionSensorEx;
extern ptrSimGetVisionSensorImg simGetVisionSensorImg;
extern ptrSimSetVisionSensorImg simSetVisionSensorImg;
extern ptrSimGetVisionSensorRes simGetVisionSensorRes;
extern ptrSimGetVisionSensorDepth simGetVisionSensorDepth;
extern ptr_simSetVisionSensorDepth _simSetVisionSensorDepth;
extern ptrSimGetObjectQuaternion simGetObjectQuaternion;
extern ptrSimSetObjectQuaternion simSetObjectQuaternion;
extern ptrSimRuckigPos simRuckigPos;
extern ptrSimRuckigVel simRuckigVel;
extern ptrSimRuckigStep simRuckigStep;
extern ptrSimRuckigRemove simRuckigRemove;
extern ptrSimGroupShapes simGroupShapes;
extern ptrSimUngroupShape simUngroupShape;
extern ptrSimConvexDecompose simConvexDecompose;
extern ptrSimQuitSimulator simQuitSimulator;
extern ptrSimSetShapeMaterial simSetShapeMaterial;
extern ptrSimGetTextureId simGetTextureId;
extern ptrSimReadTexture simReadTexture;
extern ptrSimWriteTexture simWriteTexture;
extern ptrSimCreateTexture simCreateTexture;
extern ptrSimGetShapeGeomInfo simGetShapeGeomInfo;
extern ptrSimGetObjects simGetObjects;
extern ptrSimGetObjectsInTree simGetObjectsInTree;
extern ptrSimScaleObject simScaleObject;
extern ptrSimSetShapeTexture simSetShapeTexture;
extern ptrSimGetShapeTextureId simGetShapeTextureId;
extern ptrSimCreateCollectionEx simCreateCollectionEx;
extern ptrSimAddItemToCollection simAddItemToCollection;
extern ptrSimDestroyCollection simDestroyCollection;
extern ptrSimGetCollectionObjects simGetCollectionObjects;
extern ptrSimAlignShapeBB simAlignShapeBB;
extern ptrSimRelocateShapeFrame simRelocateShapeFrame;
extern ptrSimSaveImage simSaveImage;
extern ptrSimLoadImage simLoadImage;
extern ptrSimGetScaledImage simGetScaledImage;
extern ptrSimTransformImage simTransformImage;
extern ptrSimGetQHull simGetQHull;
extern ptrSimGetDecimatedMesh simGetDecimatedMesh;
extern ptrSimCallScriptFunctionEx simCallScriptFunctionEx;
extern ptrSimGetExtensionString simGetExtensionString;
extern ptrSimComputeMassAndInertia simComputeMassAndInertia;
extern ptrSimCreateStack simCreateStack;
extern ptrSimReleaseStack simReleaseStack;
extern ptrSimCopyStack simCopyStack;
extern ptrSimPushNullOntoStack simPushNullOntoStack;
extern ptrSimPushBoolOntoStack simPushBoolOntoStack;
extern ptrSimPushInt32OntoStack simPushInt32OntoStack;
extern ptrSimPushInt64OntoStack simPushInt64OntoStack;
extern ptrSimPushFloatOntoStack simPushFloatOntoStack;
extern ptrSimPushDoubleOntoStack simPushDoubleOntoStack;
extern ptrSimPushTextOntoStack simPushTextOntoStack;
extern ptrSimPushStringOntoStack simPushStringOntoStack;
extern ptrSimPushBufferOntoStack simPushBufferOntoStack;
extern ptrSimPushUInt8TableOntoStack simPushUInt8TableOntoStack;
extern ptrSimPushInt32TableOntoStack simPushInt32TableOntoStack;
extern ptrSimPushInt64TableOntoStack simPushInt64TableOntoStack;
extern ptrSimPushFloatTableOntoStack simPushFloatTableOntoStack;
extern ptrSimPushDoubleTableOntoStack simPushDoubleTableOntoStack;
extern ptrSimPushTableOntoStack simPushTableOntoStack;
extern ptrSimInsertDataIntoStackTable simInsertDataIntoStackTable;
extern ptrSimGetStackSize simGetStackSize;
extern ptrSimPopStackItem simPopStackItem;
extern ptrSimMoveStackItemToTop simMoveStackItemToTop;
extern ptrSimGetStackItemType simGetStackItemType;
extern ptrSimGetStackStringType simGetStackStringType;
extern ptrSimGetStackBoolValue simGetStackBoolValue;
extern ptrSimGetStackInt32Value simGetStackInt32Value;
extern ptrSimGetStackInt64Value simGetStackInt64Value;
extern ptrSimGetStackFloatValue simGetStackFloatValue;
extern ptrSimGetStackDoubleValue simGetStackDoubleValue;
extern ptrSimGetStackStringValue simGetStackStringValue;
extern ptrSimGetStackTableInfo simGetStackTableInfo;
extern ptrSimGetStackUInt8Table simGetStackUInt8Table;
extern ptrSimGetStackInt32Table simGetStackInt32Table;
extern ptrSimGetStackInt64Table simGetStackInt64Table;
extern ptrSimGetStackFloatTable simGetStackFloatTable;
extern ptrSimGetStackDoubleTable simGetStackDoubleTable;
extern ptrSimUnfoldStackTable simUnfoldStackTable;
extern ptrSimDebugStack simDebugStack;
extern ptrSimCreateOctree simCreateOctree;
extern ptrSimCreatePointCloud simCreatePointCloud;
extern ptrSimSetPointCloudOptions simSetPointCloudOptions;
extern ptrSimGetPointCloudOptions simGetPointCloudOptions;
extern ptrSimInsertVoxelsIntoOctree simInsertVoxelsIntoOctree;
extern ptrSimRemoveVoxelsFromOctree simRemoveVoxelsFromOctree;
extern ptrSimInsertPointsIntoPointCloud simInsertPointsIntoPointCloud;
extern ptrSimRemovePointsFromPointCloud simRemovePointsFromPointCloud;
extern ptrSimIntersectPointsWithPointCloud simIntersectPointsWithPointCloud;
extern ptrSimGetOctreeVoxels simGetOctreeVoxels;
extern ptrSimGetPointCloudPoints simGetPointCloudPoints;
extern ptrSimInsertObjectIntoOctree simInsertObjectIntoOctree;
extern ptrSimSubtractObjectFromOctree simSubtractObjectFromOctree;
extern ptrSimInsertObjectIntoPointCloud simInsertObjectIntoPointCloud;
extern ptrSimSubtractObjectFromPointCloud simSubtractObjectFromPointCloud;
extern ptrSimCheckOctreePointOccupancy simCheckOctreePointOccupancy;
extern ptrSimOpenTextEditor simOpenTextEditor;
extern ptrSimPackTable simPackTable;
extern ptrSimUnpackTable simUnpackTable;
extern ptrSimSetReferencedHandles simSetReferencedHandles;
extern ptrSimGetReferencedHandles simGetReferencedHandles;
extern ptrSimGetShapeViz simGetShapeViz;
extern ptrSimExecuteScriptString simExecuteScriptString;
extern ptrSimGetApiFunc simGetApiFunc;
extern ptrSimGetApiInfo simGetApiInfo;
extern ptrSimGetPluginName simGetPluginName;
extern ptrSimSetPluginInfo simSetPluginInfo;
extern ptrSimGetPluginInfo simGetPluginInfo;
extern ptrSimEventNotification simEventNotification;
extern ptrSimApplyTexture simApplyTexture;
extern ptrSimSetJointDependency simSetJointDependency;
extern ptrSimGetJointDependency simGetJointDependency;
extern ptrSimGetShapeMass simGetShapeMass;
extern ptrSimSetShapeMass simSetShapeMass;
extern ptrSimGetShapeInertia simGetShapeInertia;
extern ptrSimSetShapeInertia simSetShapeInertia;
extern ptrSimIsDynamicallyEnabled simIsDynamicallyEnabled;
extern ptrSimGenerateShapeFromPath simGenerateShapeFromPath;
extern ptrSimGetClosestPosOnPath simGetClosestPosOnPath;
extern ptrSimInitScript simInitScript;
extern ptrSimModuleEntry simModuleEntry;
extern ptrSimCheckExecAuthorization simCheckExecAuthorization;
extern ptr_simSetDynamicSimulationIconCode _simSetDynamicSimulationIconCode;
extern ptr_simSetDynamicObjectFlagForVisualization _simSetDynamicObjectFlagForVisualization;
extern ptr_simGetObjectListSize _simGetObjectListSize;
extern ptr_simGetObjectFromIndex _simGetObjectFromIndex;
extern ptr_simGetObjectID _simGetObjectID;
extern ptr_simGetObjectType _simGetObjectType;
extern ptr_simGetObjectChildren _simGetObjectChildren;
extern ptr_simGetParentObject _simGetParentObject;
extern ptr_simGetObject _simGetObject;
extern ptr_simGetIkGroupObject _simGetIkGroupObject;
extern ptr_simMpHandleIkGroupObject _simMpHandleIkGroupObject;
extern ptr_simGetObjectLocalTransformation _simGetObjectLocalTransformation;
extern ptr_simSetObjectLocalTransformation _simSetObjectLocalTransformation;
extern ptr_simDynReportObjectCumulativeTransformation _simDynReportObjectCumulativeTransformation;
extern ptr_simSetObjectCumulativeTransformation _simSetObjectCumulativeTransformation;
extern ptr_simGetObjectCumulativeTransformation _simGetObjectCumulativeTransformation;
extern ptr_simIsShapeDynamicallyStatic _simIsShapeDynamicallyStatic;
extern ptr_simGetTreeDynamicProperty _simGetTreeDynamicProperty;
extern ptr_simGetDummyLinkType _simGetDummyLinkType;
extern ptr_simGetJointMode _simGetJointMode;
extern ptr_simIsJointInHybridOperation _simIsJointInHybridOperation;
extern ptr_simDisableDynamicTreeForManipulation _simDisableDynamicTreeForManipulation;
extern ptr_simIsShapeDynamicallyRespondable _simIsShapeDynamicallyRespondable;
extern ptr_simGetDynamicCollisionMask _simGetDynamicCollisionMask;
extern ptr_simGetLastParentForLocalGlobalCollidable _simGetLastParentForLocalGlobalCollidable;
extern ptr_simSetJointVelocity _simSetJointVelocity;
extern ptr_simSetJointPosition _simSetJointPosition;
extern ptr_simGetJointPosition _simGetJointPosition;
extern ptr_simSetDynamicMotorPositionControlTargetPosition _simSetDynamicMotorPositionControlTargetPosition;
extern ptr_simGetInitialDynamicVelocity _simGetInitialDynamicVelocity;
extern ptr_simSetInitialDynamicVelocity _simSetInitialDynamicVelocity;
extern ptr_simGetInitialDynamicAngVelocity _simGetInitialDynamicAngVelocity;
extern ptr_simSetInitialDynamicAngVelocity _simSetInitialDynamicAngVelocity;
extern ptr_simGetStartSleeping _simGetStartSleeping;
extern ptr_simGetWasPutToSleepOnce _simGetWasPutToSleepOnce;
extern ptr_simGetDynamicsFullRefreshFlag _simGetDynamicsFullRefreshFlag;
extern ptr_simSetDynamicsFullRefreshFlag _simSetDynamicsFullRefreshFlag;
extern ptr_simSetShapeDynamicVelocity _simSetShapeDynamicVelocity;
extern ptr_simGetAdditionalForceAndTorque _simGetAdditionalForceAndTorque;
extern ptr_simClearAdditionalForceAndTorque _simClearAdditionalForceAndTorque;
extern ptr_simGetJointPositionInterval _simGetJointPositionInterval;
extern ptr_simGetJointType _simGetJointType;
extern ptr_simGetDynamicMotorTargetPosition _simGetDynamicMotorTargetPosition;
extern ptr_simGetDynamicMotorTargetVelocity _simGetDynamicMotorTargetVelocity;
extern ptr_simGetDynamicMotorMaxForce _simGetDynamicMotorMaxForce;
extern ptr_simGetDynamicMotorUpperLimitVelocity _simGetDynamicMotorUpperLimitVelocity;
extern ptr_simSetDynamicMotorReflectedPositionFromDynamicEngine _simSetDynamicMotorReflectedPositionFromDynamicEngine;
extern ptr_simSetJointSphericalTransformation _simSetJointSphericalTransformation;
extern ptr_simAddForceSensorCumulativeForcesAndTorques _simAddForceSensorCumulativeForcesAndTorques;
extern ptr_simAddJointCumulativeForcesOrTorques _simAddJointCumulativeForcesOrTorques;
extern ptr_simGetGeomWrapFromGeomProxy _simGetGeomWrapFromGeomProxy;
extern ptr_simGetPurePrimitiveType _simGetPurePrimitiveType;
extern ptr_simIsGeomWrapGeometric _simIsGeomWrapGeometric;
extern ptr_simIsGeomWrapConvex _simIsGeomWrapConvex;
extern ptr_simGetGeometricCount _simGetGeometricCount;
extern ptr_simGetAllGeometrics _simGetAllGeometrics;
extern ptr_simGetPurePrimitiveSizes _simGetPurePrimitiveSizes;
extern ptr_simMakeDynamicAnnouncement _simMakeDynamicAnnouncement;
extern ptr_simGetVerticesLocalFrame _simGetVerticesLocalFrame;
extern ptr_simGetHeightfieldData _simGetHeightfieldData;
extern ptr_simGetCumulativeMeshes _simGetCumulativeMeshes;
extern ptr_simGetMass _simGetMass;
extern ptr_simGetLocalInertiaInfo _simGetLocalInertiaInfo;
extern ptr_simGetGravity _simGetGravity;
extern ptr_simGetTimeDiffInMs _simGetTimeDiffInMs;
extern ptr_simDoEntitiesCollide _simDoEntitiesCollide;
extern ptr_simGetDistanceBetweenEntitiesIfSmaller _simGetDistanceBetweenEntitiesIfSmaller;
extern ptr_simHandleJointControl _simHandleJointControl;
extern ptr_simHandleCustomContact _simHandleCustomContact;
extern ptr_simGetPureHollowScaling _simGetPureHollowScaling;
extern ptr_simGetJointDynCtrlMode _simGetJointDynCtrlMode;
extern ptr_simDynCallback _simDynCallback;

#include "simLib-old.h"
#endif
